
// Bolívar
'achí': 'Located on the banks of the Cauca River, Achí is known for its amphibious culture and rice production.',
    'altos del rosario': 'A traditional town in the Montes de María, surrounded by hills and known for its resilient community.',
        'arenal': 'A mining and agricultural municipality with a strong connection to the Serranía de San Lucas.',
            'arjona': 'Known as the "Capital of the Bollo de Mazorca," Arjona is a folklore hub with vibrant cattle ranching traditions.',
                'arroyohondo': 'A small town near the Dique Canal, known for its fishing and agricultural lifestyle.',
                    'barranco de loba': 'A river port on the Magdalena, rich in legends and traditional tambora music.',
                        'brazuelo de papayal': 'A riverside community deeply connected to the Magdalena River cycles and fishing capability.',
                            'calamar': 'A strategic port located at the entrance of the Dique Canal, serving as a gateway between the Magdalena River and Cartagena.',
                                'cantagallo': 'Located in the south, known for its oil industry and river landscapes along the Magdalena.',
                                    'cartagena': 'The "Heroic City," a UNESCO World Heritage site famous for its colonial walled city, fortress, and vibrant Caribbean culture.',
                                        'cartagena de indias': 'The "Heroic City," a UNESCO World Heritage site famous for its colonial walled city, fortress, and vibrant Caribbean culture.',
                                            'cicuco': 'Known for its oil history and its location on the Mompox Depression.',
                                                'clemencia': 'A municipality near Cartagena, known for its agriculture and proximity to the El Totumo mud volcano.',
                                                    'córdoba': 'A town in the Montes de María, known for its agricultural production and resilience.',
                                                        'el carmen de bolívar': 'The heart of the Montes de María, famous for its avocado and tobacco production, and a center of resilience and peace-building.',
                                                            'el guamo': 'Located in the Montes de María, it is known for its rolling hills and agricultural landscapes.',
                                                                'el peñón': 'A riverside town with access to the Magdalena, known for its fishing and agricultural activities.',
                                                                    'hatillo de loba': 'A picturesque river town known for its colonial church and amphibious culture.',
                                                                        'magangué': 'The "Capital of the Rivers," a major commercial hub where the Cauca meets the Magdalena.',
                                                                            'mahates': 'Home to the San Basilio de Palenque (a corregimiento), the first free town in the Americas and a UNESCO heritage site.',
                                                                                'margarita': 'Known as the "Orange Capital," located on the Mompox Depression island.',
                                                                                    'maría la baja': 'Famous for its extensive palm oil plantations and the large Matuya irrigation district.',
                                                                                        'mompós': 'A UNESCO World Heritage site frozen in time, famous for its filigree jewelry, Holy Week, and jazz festival.',
                                                                                            'mompos': 'A UNESCO World Heritage site frozen in time, famous for its filigree jewelry, Holy Week, and jazz festival.',
                                                                                                'montecristo': 'Reviewing the gold mining history and river connection in the south of the department.',
                                                                                                    'morales': 'An agricultural and fishing center on the banks of the Magdalena River.',
                                                                                                        'norosí': 'Traditionally a mining town with a strong gold-working heritage.',
                                                                                                            'pinillos': 'A river municipality surrounded by the Magdalena and Cauca rivers, known for its water-based festivals.',
                                                                                                                'regidor': 'A port town on the Magdalena River, serving as a connector for southern Bolívar.',
                                                                                                                    'río viejo': 'Located in the south, known for its natural wealth and river trade.',
                                                                                                                        'san cristóbal': 'A municipality located along the Dique Canal, with a focus on fishing and agriculture.',
                                                                                                                            'san estanislao': 'Known as "Arenal," a town on the Dique Canal famous for its sand and river economy.',
                                                                                                                                'san fernando': 'A historic town near Mompós, known for its colonial architecture and river traditions.',
                                                                                                                                    'san jacinto': 'World-famous for its handicrafts, specifically the colorful hammocks and gaitas (flutes).',
                                                                                                                                        'san jacinto del cauca': 'Located in the wetland region of the Mojana, known for its amphibious adaptation.',
                                                                                                                                            'san juan nepomuceno': 'Gateway to the Los Colorados Flora and Fauna Sanctuary, home to howler monkeys.',
                                                                                                                                                'san martín de loba': 'A town with a rich history of mining and river legends, located on the Loba arm of the river.',
                                                                                                                                                    'san pablo': 'A major river port in southern Bolívar, bustling with commerce and agriculture.',
                                                                                                                                                        'santa catalina': 'Famous for the El Totumo Volcano nearby and its coastal location.',
                                                                                                                                                            'santa rosa': 'A town near Cartagena, serving as an urban expansion and industrial hub.',
                                                                                                                                                                'santa rosa del sur': 'The "Capital of the South," a mining and agricultural center in the Serranía de San Lucas.',
                                                                                                                                                                    'simití': 'One of the oldest towns in the region, located on a large swamp (ciénaga) with a beautiful colonial church.',
                                                                                                                                                                        'soplaviento': 'Located on the Dique Canal, famous for its fishing economy and river culture.',
                                                                                                                                                                            'talaigua nuevo': 'Known for its proximity to Mompós and the "Farotas" dance tradition.',
                                                                                                                                                                                'tiquisio': 'A mining and agricultural town known as "Puerto Rico" on the river.',
                                                                                                                                                                                    'turbaco': 'A hilltop town near Cartagena with a cooler climate, famous for its botanical garden and water springs.',
                                                                                                                                                                                        'turbaná': 'Located near Cartagena, known for its limestone hills and proximity to the city.',
                                                                                                                                                                                            'villanueva': 'A town near Cartagena known for its limestone quarries and skilled stonemasons.',
                                                                                                                                                                                                'zambrano': 'A major port on the Magdalena River, known for its tobacco history and bridge connectivity.',
