
// Bolívar
'achí': '/images/city_achi.png',
    'achi': '/images/city_achi.png',
        'altos del rosario': '/images/city_altos_del_rosario.png',
            'arenal': '/images/city_arenal.png',
                'arjona': '/images/city_arjona.png',
                    'arroyohondo': '/images/city_arroyohondo.png',
                        'barranco de loba': '/images/city_barranco_de_loba.png',
                            'brazuelo de papayal': '/images/city_brazuelo_de_papayal.png',
                                'calamar': '/images/city_calamar_bolivar.png',
                                    'cantagallo': '/images/city_cantagallo.png',
                                        'cartagena': '/images/city_cartagena.png',
                                            'cartagena de indias': '/images/city_cartagena.png',
                                                'cicuco': '/images/city_cicuco.png',
                                                    'clemencia': '/images/city_clemencia.png',
                                                        'córdoba': '/images/city_cordoba.png',
                                                            'cordoba': '/images/city_cordoba.png',
                                                                'el carmen de bolívar': '/images/city_el_carmen_de_bolivar.png',
                                                                    'el carmen de bolivar': '/images/city_el_carmen_de_bolivar.png',
                                                                        'el guamo': '/images/city_el_guamo.png',
                                                                            'el peñón': '/images/city_el_penon_bolivar.png',
                                                                                'el penon': '/images/city_el_penon_bolivar.png',
                                                                                    'el penon bolivar': '/images/city_el_penon_bolivar.png',
                                                                                        'hatillo de loba': '/images/city_hatillo_de_loba.png',
                                                                                            'magangué': '/images/city_magangue.png',
                                                                                                'magangue': '/images/city_magangue.png',
                                                                                                    'mahates': '/images/city_mahates.png',
                                                                                                        'margarita': '/images/city_margarita.png',
                                                                                                            'maría la baja': '/images/city_maria_la_baja.png',
                                                                                                                'maria la baja': '/images/city_maria_la_baja.png',
                                                                                                                    'mompós': '/images/city_mompos.png',
                                                                                                                        'mompos': '/images/city_mompos.png',
                                                                                                                            'montecristo': '/images/city_montecristo.png',
                                                                                                                                'morales': '/images/city_morales_bolivar.png',
                                                                                                                                    'norosí': '/images/city_norosi.png',
                                                                                                                                        'norosi': '/images/city_norosi.png',
                                                                                                                                            'pinillos': '/images/city_pinillos.png',
                                                                                                                                                'regidor': '/images/city_regidor.png',
                                                                                                                                                    'río viejo': '/images/city_rio_viejo.png',
                                                                                                                                                        'rio viejo': '/images/city_rio_viejo.png',
                                                                                                                                                            'san cristóbal': '/images/city_san_cristobal_bolivar.png',
                                                                                                                                                                'san cristobal': '/images/city_san_cristobal_bolivar.png',
                                                                                                                                                                    'san estanislao': '/images/city_san_estanislao.png',
                                                                                                                                                                        'san fernando': '/images/city_san_fernando_bolivar.png',
                                                                                                                                                                            'san jacinto': '/images/city_san_jacinto.png',
                                                                                                                                                                                'san jacinto del cauca': '/images/city_san_jacinto_del_cauca.png',
                                                                                                                                                                                    'san juan nepomuceno': '/images/city_san_juan_nepomuceno.png',
                                                                                                                                                                                        'san martín de loba': '/images/city_san_martin_de_loba.png',
                                                                                                                                                                                            'san martin de loba': '/images/city_san_martin_de_loba.png',
                                                                                                                                                                                                'san pablo': '/images/city_san_pablo_bolivar.png',
                                                                                                                                                                                                    'santa catalina': '/images/city_santa_catalina.png',
                                                                                                                                                                                                        'santa rosa': '/images/city_santa_rosa_bolivar.png',
                                                                                                                                                                                                            'santa rosa del sur': '/images/city_santa_rosa_del_sur.png',
                                                                                                                                                                                                                'simití': '/images/city_simiti.png',
                                                                                                                                                                                                                    'simiti': '/images/city_simiti.png',
                                                                                                                                                                                                                        'soplaviento': '/images/city_soplaviento.png',
                                                                                                                                                                                                                            'talaigua nuevo': '/images/city_talaigua_nuevo.png',
                                                                                                                                                                                                                                'tiquisio': '/images/city_tiquisio.png',
                                                                                                                                                                                                                                    'turbaco': '/images/city_turbaco.png',
                                                                                                                                                                                                                                        'turbaná': '/images/city_turbana.png',
                                                                                                                                                                                                                                            'turbana': '/images/city_turbana.png',
                                                                                                                                                                                                                                                'villanueva': '/images/city_villanueva_bolivar.png',
                                                                                                                                                                                                                                                    'zambrano': '/images/city_zambrano.png',
