import { getAssetPath } from './utils';

export const cityImages: Record<string, string> = {
    'cartagena': '/images/city_cartagena.png',
    'cartagena de indias': '/images/city_cartagena.png',
    'mompós': '/images/city_mompos.png',
    'mompos': '/images/city_mompos.png',
    'santa cruz de mompós': '/images/city_mompos.png',
    'san jacinto': '/images/city_san_jacinto.png',
    'magangué': '/images/city_magangue.png',
    'magangue': '/images/city_magangue.png',
    'el carmen de bolívar': '/images/city_el_carmen_bolivar.png',
    'turbaco': '/images/city_turbaco.png',
    'san juan nepomuceno': '/images/city_san_juan_nepomuceno.png',
    'santa rosa del sur': '/images/city_santa_rosa_del_sur.png',
    'mahates': '/images/city_mahates.png',
    'arjona': '/images/city_arjona.png',
    'maría la baja': '/images/city_maria_la_baja.png',
    'bolivar-villanueva': '/images/city_villanueva_bolivar.png',
    'bolivar-santa rosa': '/images/city_santa_rosa_bolivar.png',
    'clemencia': '/images/city_clemencia.png',
    'bolivar-calamar': '/images/city_calamar_bolivar.png',
    'san estanislao': '/images/city_san_estanislao.png',
    'el guamo': '/images/city_el_guamo.png',
    'bolivar-córdoba': '/images/city_cordoba_bolivar.png',
    'soplaviento': '/images/city_soplaviento.png',
    'bolivar-san cristóbal': '/images/city_san_cristobal_bolivar.png',
    'zambrano': '/images/city_zambrano.png',
    'pinillos': '/images/city_pinillos.png',
    'tiquisio': '/images/city_tiquisio.png',
    'achí': '/images/city_achi.png',
    'altos del rosario': '/images/city_altos_del_rosario.png',
    'barranco de loba': '/images/city_barranco_de_loba.png',
    'cantagallo': '/images/city_cantagallo.png',
    'hatillo de loba': '/images/city_hatillo_de_loba.png',
    'montecristo': '/images/city_montecristo.png',
    'bolivar-morales': '/images/city_morales_bolivar.png',
    'norosí': '/images/city_norosi.png',
    'regidor': '/images/city_regidor.png',
    'río viejo': '/images/city_rio_viejo.png',
    'bolivar-san jacinto del cauca': '/images/city_san_jacinto_del_cauca.png',
    'san martín de loba': '/images/city_san_martin_de_loba.png',
    'santa catalina': '/images/city_santa_catalina.png',
    'bolivar-san pablo': '/images/city_san_pablo_bolivar.png',
    'bolivar-san fernando': '/images/city_san_fernando_bolivar.png',
    'simití': '/images/city_simiti.png',
    'talaigua nuevo': '/images/city_talaigua_nuevo.png',
    'turbaná': '/images/city_turbana.png',
    'arroyohondo': '/images/city_arroyohondo.png',
    'cicuco': '/images/city_cicuco.png',
    'margarita': '/images/city_margarita.png',
    'arenal': '/images/city_arenal.png',
    'bolivar-arenal': '/images/city_arenal.png',
    'bolivar-el peñón': '/images/city_el_penon_bolivar.png',
    'bolivar-el peñon': '/images/city_el_penon_bolivar.png',
    'san pablo de borbur': '/images/city_san_pablo_de_borbur.png',
    'bolivar-san pablo de borbur': '/images/city_san_pablo_de_borbur.png',
    'santander-bucaramanga': '/images/city_bucaramanga.png',
    'manizales': '/images/city-manizales.png',
    'pereira': '/images/city-pereira.png',
    'armenia': '/images/city-armenia.png',
    'cúcuta': '/images/city-cucuta.png',
    'cucuta': '/images/city-cucuta.png',
    'ibagué': '/images/city-ibague.png',
    'ibague': '/images/city-ibague.png',
    'neiva': '/images/city_neiva.png',
    'pasto': '/images/city_pasto.png',
    'villavicencio': '/images/city_villavicencio.png',
    'popayán': '/images/city_popayan.png',
    'popayan': '/images/city_popayan.png',
    'popay': '/images/city_popayan.png',
    'valledupar': '/images/city_valledupar.png',
    'montería': '/images/city_monteria.png',
    'monteria': '/images/city_monteria.png',
    'monter': '/images/city_monteria.png',
    'tunja': '/images/city_tunja.png',
    'riohacha': '/images/city_riohacha.png',
    'quibdó': '/images/city_quibdo.png',
    'quibdo': '/images/city_quibdo.png',
    'quibd': '/images/city_quibdo.png',
    'leticia': '/images/city_leticia.png',
    'florencia': '/images/city_florencia.png',
    'yopal': '/images/city_yopal.png',
    'arauca': '/images/city_arauca.png',
    'sincelejo': '/images/city_sincelejo.png',
    'mocoa': '/images/city_mocoa.png',
    'inírida': '/images/city_inirida.png',
    'inirida': '/images/city_inirida.png',
    'mitu': '/images/city_mitu.png',
    'mitú': '/images/city_mitu.png',
    'buenavista': '/images/city_buenavista.png',
    'circasia': '/images/city_circasia.png',
    'córdoba': '/images/city_cordoba.png',
    'cordoba': '/images/city_cordoba.png',
    'filandia': '/images/city_filandia.png',
    'la tebaida': '/images/city_la_tebaida.png',
    'montenegro': '/images/city_montenegro.png',
    'pijao': '/images/city_pijao.png',
    'quimbaya': '/images/city_quimbaya.png',
    'salento': '/images/city_salento.png',
    'leticia': '/images/city_leticia.png',
    'puerto nariño': '/images/city_puerto_narino.png',
    'calarcá': '/images/city_calarca.png',
    'calarca': '/images/city_calarca.png',
    'génova': '/images/city_genova.png',
    'genova': '/images/city_genova.png',
    'mirití paraná': '/images/city_miriti_parana.png',
    'miriti paraná': '/images/city_miriti_parana.png',
    'mirití parana': '/images/city_miriti_parana.png',
    'miriti parana': '/images/city_miriti_parana.png',
    'puerto narino': '/images/city_puerto_narino.png',
    'el encanto': '/images/city_el_encanto.png',
    'la chorrera': '/images/city_la_chorrera.png',
    'la pedrera': '/images/city_la_pedrera.png',
    'la victoria': '/images/city_la_victoria.png',
    'puerto arica': '/images/city_puerto_arica.png',
    'puerto santander': '/images/city_puerto_santander.png',
    'tarapacá': '/images/city_tarapaca.png',
    'tarapaca': '/images/city_tarapaca.png',
    'puerto alegría': '/images/city_puerto_alegria.png',
    'puerto alegria': '/images/city_puerto_alegria.png',
    'puerto carreño': '/images/city_puerto_carreno.png',
    'puerto carreno': '/images/city_puerto_carreno.png',
    'guatapé': '/images/city_guatape.png',
    'guatape': '/images/city_guatape.png',
    'jardín': '/images/city_jardin.png',
    'jardin': '/images/city_jardin.png',
    'jericó': '/images/city_jerico.png',
    'jerico': '/images/city_jerico.png',
    'santafé de antioquia': '/images/city_santafe_antioquia.png',
    'santafe de antioquia': '/images/city_santafe_antioquia.png',
    'santa rosa de osos': '/images/city_santa_rosa_osos.png',
    'támesis': '/images/city_tamesis.png',
    'tamesis': '/images/city_tamesis.png',
    'rionegro': '/images/city_rionegro.png',
    'envigado': '/images/city_envigado.png',
    'sabaneta': '/images/city_sabaneta.png',
    'itagüí': '/images/city_itagui.png',
    'itagui': '/images/city_itagui.png',
    'la ceja': '/images/city_la_ceja.png',
    'el carmen de viboral': '/images/city_el_carmen_viboral.png',
    'villa de leyva': '/images/city_villa_de_leyva.png',
    'paipa': '/images/city_paipa.png',
    'monguí': '/images/city_mongui.png',
    'mongui': '/images/city_mongui.png',
    'ráquira': '/images/city_raquira.png',
    'raquira': '/images/city_raquira.png',
    'sogamoso': '/images/city_sogamoso.png',
    'duitama': '/images/city_duitama.png',
    'iza': '/images/city_iza.png',
    'nobsa': '/images/city_nobsa.png',
    'aquitania': '/images/city_aquitania.png',
    'tibasosa': '/images/city_tibasosa.png',
    'sáchica': '/images/city_sachica.png',
    'sachica': '/images/city_sachica.png',
    'cucaita': '/images/city_cucaita.png',
    'chiquinquirá': '/images/city_chiquinquira.png',
    'moniquirá': '/images/city_moniquira.png',
    'garagoa': '/images/city_garagoa.png',
    'guateque': '/images/city_guateque.png',
    'puerto boyacá': '/images/city_puerto_boyaca.png',
    'santa rosa de viterbo': '/images/city_santa_rosa_de_viterbo.png',
    'el cocuy': '/images/city_el_cocuy.png',
    'muzo': '/images/city_muzo.png',
    'ramiriquí': '/images/city_ramiriqui.png',
    'jenesano': '/images/city_jenesano.png',
    'sora': '/images/city_sora.png',
    'soracá': '/images/city_soraca.png',
    'sutamarchán': '/images/city_sutamarchan.png',
    'tinjacá': '/images/city_tinjaca.png',
    'motavita': '/images/city_motavita.png',
    'arcabuco': '/images/city_arcabuco.png',
    'belén': '/images/city_belen.png',
    'boavita': '/images/city_boavita.png',
    'boyacá': '/images/city_boyaca_town.png',
    'buenavista-boyaca': '/images/city_buenavista_boyaca.png',
    'chivatá': '/images/city_chivata.png',
    'chivor': '/images/city_chivor.png',
    'cómbita': '/images/city_combita.png',
    'güicán': '/images/city_guican.png',
    'firavitoba': '/images/city_firavitoba.png',
    'gachantivá': '/images/city_gachantiva.png',
    'miraflores': '/images/city_miraflores.png',
    'samacá': '/images/city_samaca.png',
    'tota': '/images/city_tota.png',
    'tuta': '/images/city_tuta.png',
    'ventaquemada': '/images/city_ventaquemada.png',
    'soatá': '/images/city_soata.png',
    'turmequé': '/images/city_turmeque.png',
    'togüí': '/images/city_togui.png',
    'tenza': '/images/city_tenza.png',
    'sotaquirá': '/images/city_sotaquira.png',
    'siachoque': '/images/city_siachoque.png',
    'saboyá': '/images/city_saboya.png',
    'nuevo colón': '/images/city_nuevo_colon.png',
    'otanche': '/images/city_otanche.png',
    'zetaquira': '/images/city_zetaquira.png',
    'macanal': '/images/city_macanal.png',
    'cubará': '/images/city_cubara.png',
    'chiscas': '/images/city_chiscas.png',
    'coper': '/images/city_coper.png',
    'betéitiva': '/images/city_beteitiva.png',
    'almeida': '/images/city_almeida.png',
    'berbeo': '/images/city_berbeo.png',
    'briceño': '/images/city_briceno.png',
    'briceno': '/images/city_briceno.png',
    'buena vista': '/images/city_buena_vista.png',
    'busbanzá': '/images/city_busbanza.png',
    'caldas': '/images/city_caldas.png',
    'campohermoso': '/images/city_campohermoso.png',
    'cerinza': '/images/city_cerinza.png',
    'chinavita': '/images/city_chinavita.png',
    'chíquiza': '/images/city_chiquiza.png',
    'chita': '/images/city_chita.png',
    'chitaraque': '/images/city_chitaraque.png',
    'ciénega': '/images/city_cienega.png',
    'corrales': '/images/city_corrales.png',
    'covarachía': '/images/city_covarachia.png',
    'cuítiva': '/images/city_cuitiva.png',
    'el espino': '/images/city_el_espino.png',
    'floresta': '/images/city_floresta.png',
    'gámeza': '/images/city_gameza.png',
    'gameza': '/images/city_gameza.png',
    'guacamayas': '/images/city_guacamayas.png',
    'guayatá': '/images/city_guayata.png',
    'boyacá-jericó': '/images/city_jerico.png',
    'la capilla': '/images/city_la_capilla.png',
    'la uvita': '/images/city_la_uvita.png',
    'boyacá-la victoria': '/images/city_la_victoria.png',
    'labranzagrande': '/images/city_labranzagrande.png',
    'maripí': '/images/city_maripi.png',
    'mongua': '/images/city_mongua.png',
    'oicatá': '/images/city_oicata.png',
    'pachavita': '/images/city_pachavita.png',
    'páez': '/images/city_paez.png',
    'pajarito': '/images/city_pajarito.png',
    'panqueba': '/images/city_panqueba.png',
    'santana': '/images/city_santana.png',
    'sativanorte': '/images/city_sativanorte.png',
    'sativasur': '/images/city_sativasur.png',
    'pauna': '/images/city_pauna.png',
    'paya': '/images/city_paya.png',
    'paz de río': '/images/city_paz_de_rio.png',
    'pesca': '/images/city_pesca.png',
    'pisba': '/images/city_pisba.png',
    'quípama': '/images/city_quipama.png',
    'rondón': '/images/city_rondon.png',
    'socha': '/images/city_socha.png',
    'socotá': '/images/city_socota.png',
    'socota': '/images/city_socota.png',
    'somondoco': '/images/city_somondoco.png',
    'susacón': '/images/city_susacon.png',
    'susacon': '/images/city_susacon.png',
    'sutatenza': '/images/city_sutatenza.png',
    'tasco': '/images/city_tasco.png',
    'tibaná': '/images/city_tibana.png',
    'tibana': '/images/city_tibana.png',
    'tipacoque': '/images/city_tipacoque.png',
    'tununguá': '/images/city_tunungua.png',
    'tunungua': '/images/city_tunungua.png',
    'tutazá': '/images/city_tutaza.png',
    'tutaza': '/images/city_tutaza.png',
    'tópaga': '/images/city_topaga.png',
    'topaga': '/images/city_topaga.png',
    'úmbita': '/images/city_umbita.png',
    'umbita': '/images/city_umbita.png',
    'viracachá': '/images/city_viracacha.png',
    'viracacha': '/images/city_viracacha.png',
    'san eduardo': '/images/city_san_eduardo.png',
    'san josé de pare': '/images/city_san_jose_de_pare.png',
    'san luis de gaceno': '/images/city_san_luis_de_gaceno.png',
    'san mateo': '/images/city_san_mateo.png',
    'san miguel de sema': '/images/city_san_miguel_de_sema.png',
    'santa maría': '/images/city_santa_maria.png',
    'santa sofía': '/images/city_santa_sofia.png',
    'san gil': '/images/city_san_gil.png',
    'barichara': '/images/city_barichara.png',
    'girón': '/images/city_giron.png',
    'giron': '/images/city_giron.png',
    'socorro': '/images/city_socorro.png',
    'zapatoca': '/images/city_zapatoca.png',
    'curití': '/images/city_curiti.png',
    'curiti': '/images/city_curiti.png',
    'guadalupe': '/images/city_guadalupe.png',
    'barrancabermeja': '/images/city_barrancabermeja.png',
    'floridablanca': '/images/city_floridablanca.png',
    'piedecuesta': '/images/city_piedecuesta.png',
    'málaga': '/images/city_malaga.png',
    'malaga': '/images/city_malaga.png',
    'vélez': '/images/city_velez.png',
    'velez': '/images/city_velez.png',
    'villanueva': '/images/city_villanueva.png',
    'aratoca': '/images/city_aratoca.png',
    'barbosa': '/images/city_barbosa.png',
    'charalá': '/images/city_charala.png',
    'charala': '/images/city_charala.png',
    'cimitarra': '/images/city_cimitarra.png',
    'el carmen de chucurí': '/images/city_el_carmen_de_chucuri.png',
    'el carmen de chucuri': '/images/city_el_carmen_de_chucuri.png',
    'los santos': '/images/city_los_santos.png',
    'oiba': '/images/city_oiba.png',
    'páramo': '/images/city_paramo.png',
    'paramo': '/images/city_paramo.png',
    'puente nacional': '/images/city_puente_nacional.png',
    'san vicente de chucurí': '/images/city_san_vicente_de_chucuri.png',
    'san vicente de chucuri': '/images/city_san_vicente_de_chucuri.png',
    'suaita': '/images/city_suaita.png',
    'valle de san josé': '/images/city_valle_de_san_jose.png',
    'valle de san jose': '/images/city_valle_de_san_jose.png',
    'cepitá': '/images/city_cepita.png',
    'cepita': '/images/city_cepita.png',
    'pinchote': '/images/city_pinchote.png',
    'santander-albania': '/images/city_albania.png',
    'betulia': '/images/city_betulia.png',
    'bolívar': '/images/city_bolivar.png',
    'bolivar': '/images/city_bolivar.png',
    'capitanejo': '/images/city_capitanejo.png',
    'cerrito': '/images/city_cerrito.png',
    'contratación': '/images/city_contratacion.png',
    'contratacion': '/images/city_contratacion.png',
    'florián': '/images/city_florian.png',
    'florian': '/images/city_florian.png',
    'gambita': '/images/city_gambita.png',
    'jordán': '/images/city_jordan.png',
    'jordan': '/images/city_jordan.png',
    'la belleza': '/images/city_la_belleza.png',
    'landázuri': '/images/city_landazuri.png',
    'landazuri': '/images/city_landazuri.png',
    'lebríja': '/images/city_lebrija.png',
    'lebrija': '/images/city_lebrija.png',
    'mogotes': '/images/city_mogotes.png',
    'puerto wilches': '/images/city_puerto_wilches.png',
    'santander-san andrés': '/images/city_san_andres_santander.png',
    'santander-sabana de torres': '/images/city_sabana_torres.png',
    'santander-rionegro': '/images/city_rionegro_santander.png',
    'santander-california': '/images/city_california.png',
    'santander-vetas': '/images/city_vetas.png',
    'santander-matanza': '/images/city_matanza.png',
    'santander-suratá': '/images/city_surata.png',
    'santander-tona': '/images/city_tona.png',
    'santander-simacota': '/images/city_simacota.png',
    'santander-sucre': '/images/city_sucre_santander.png',
    'santander-la paz': '/images/city_la_paz_santander.png',
    'santander-el playón': '/images/city_el_playon.png',
    'santander-puerto parra': '/images/city_puerto_parra.png',
    'santander-aguada': '/images/city_aguada.png',
    'santander-cabrera': '/images/city_cabrera.png',
    'santander-carcasí': '/images/city_carcasi.png',
    'santander-charta': '/images/city_charta.png',
    'santander-chipatá': '/images/city_chipata.png',
    'santander-concepción': '/images/city_concepcion.png',
    'santander-confines': '/images/city_confines.png',
    'santander-coromoro': '/images/city_coromoro.png',
    'santander-el guacamayo': '/images/city_el_guacamayo.png',
    'santander-encino': '/images/city_encino.png',
    'santander-enciso': '/images/city_enciso.png',
    'santander-galán': '/images/city_galan.png',
    'santander-guaca': '/images/city_guaca.png',
    'santander-guapotá': '/images/city_guapota.png',
    'santander-guavatá': '/images/city_guavata.png',
    'santander-güepsa': '/images/city_guepsa.png',
    'santander-jesús maría': '/images/city_jesus_maria.png',
    'santander-macaravita': '/images/city_macaravita.png',
    'santander-molagavita': '/images/city_molagavita.png',
    'santander-ocamonte': '/images/city_ocamonte.png',
    'santander-onzaga': '/images/city_onzaga.png',
    'santander-palmar': '/images/city_palmar.png',
    'santander-san joaquín': '/images/city_san_joaquin.png',
    'santander-san miguel': '/images/city_san_miguel.png',
    'santander-santa bárbara': '/images/city_santa_barbara.png',
    'santander-san josé de miranda': '/images/city_san_jose_de_miranda.png',
    'santander-santa helena del opón': '/images/city_santa_helena_del_opon.png',
    'santander-san benito': '/images/city_san_benito.png',
    'santander-hato': '/images/city_hato.png',
    'santander-chimá': '/images/city_chima.png',
    'santander-el peñón': '/images/city_el_penon.png',
    'bogotá': '/images/city-bogota.png',
    'bogota': '/images/city-bogota.png',
    'bogot': '/images/city-bogota.png',
    'santafé de bogotá': '/images/city-bogota.png',
    'santafe de bogota': '/images/city-bogota.png',
    'medellín': '/images/city-medellin.png',
    'medellin': '/images/city-medellin.png',
    'medell': '/images/city-medellin.png',
    'cali': '/images/city-cali.png',
    'santiago de cali': '/images/city-cali.png',
    'barranquilla': '/images/city-barranquilla.png',
    'santa marta': '/images/city-santa-marta.png',
    'san andrés': '/images/city-san-andres.png',
    'san andres': '/images/city-san-andres.png',
    'san andr': '/images/city-san-andres.png'
};

export function getCityImage(cityName: string, departmentName?: string): string {
    const name = cityName.toLowerCase();
    const dept = departmentName?.toLowerCase();

    // Check for specific department-city mapping first to handle name collisions
    if (dept) {
        const specificKey = `${dept}-${name}`;
        if (cityImages[specificKey]) return getAssetPath(cityImages[specificKey]);
    }

    for (const [key, value] of Object.entries(cityImages)) {
        if (name === key || name.includes(key) || key.includes(name)) {
            return getAssetPath(value);
        }
    }

    if (cityImages[name]) return getAssetPath(cityImages[name]);

    return `https://source.unsplash.com/800x600/?colombia,${cityName}`;
}

export const cityOverviews: Record<string, string> = {
    // Boyacá
    'villa de leyva': 'Famous for its massive cobblestone plaza and beautifully preserved white colonial buildings.',
    'salento': 'The colorful gateway to the Cocora Valley, home to the Quindío Wax Palm, the world\'s tallest palm tree. This picturesque town is the heart of the Eje Cafetero, where travelers can visit traditional fincas to observe the manual harvesting and roasting of world-class Colombian coffee.',
    'leticia': 'The gateway to the Amazon rainforest, Leticia is a unique tri-border town where Colombia, Brazil, and Peru meet. It is a hub for immersive jungle expeditions, nocturnal wildlife spotting, and sustainable travel to vehicle-free towns like Puerto Nariño.',
    'puerto nariño': 'A pioneer in sustainable tourism, Puerto Nariño is a vehicle-free town on the banks of the Amazon. It offers a peaceful retreat into Ticuna indigenous culture and the immense biodiversity of the rainforest.',
    'bogotá': 'The Andean political and cultural heart of Colombia, situated at 2,625 meters. Known for its "perpetual spring" and the historic La Candelaria district, it houses the world-class Gold Museum (Museo del Oro) and the Botero Museum. Visitors can ascend Mount Monserrate for panoramic views or explore the affluent northern hubs like Zona T and Usaquén, famous for their high-end dining and nightlife.',
    'bogota': 'The Andean political and cultural heart of Colombia, situated at 2,625 meters. Known for its "perpetual spring" and the historic La Candelaria district, it houses the world-class Gold Museum (Museo del Oro) and the Botero Museum. Visitors can ascend Mount Monserrate for panoramic views or explore the affluent northern hubs like Zona T and Usaquén, famous for their high-end dining and nightlife.',
    'tunja': 'The capital of Boyacá and the highest capital city in Colombia. It features a rich colonial heritage, historic churches, and was built on the site of the ancient Muisca capital Hunza.',
    'paipa': 'Known for the serene Lake Sochagota and its relaxing medicinal thermal springs.',
    'monguí': 'A "Pueblo Patrimonio" of Colombia, famous for its historic stone bridge and hand-stitched soccer ball industry.',
    'raquira': 'The craft capital of Boyacá, famous for its extremely colorful pottery shops and colonial charm.',
    'ráquira': 'The craft capital of Boyacá, famous for its extremely colorful pottery shops and colonial charm.',
    'sogamoso': 'Home to the Sun Temple of the Muiscas, an important site of indigenous heritage.',
    'duitama': 'Features the "Pueblito Boyacense," a charming area representing the architecture of the region\'s diverse towns.',
    'iza': 'A peaceful colonial town known for its green hills and traditional dessert market.',
    'nobsa': 'Renowned for its high-quality wool crafts, especially traditional ruanas and blankets.',
    'aquitania': 'Offers stunning panoramic views of Lake Tota, the largest lake in Colombia.',
    'tibasosa': 'A picturesque colonial town famous for its beautiful gardens and Feijoa fruit products.',
    'sáchica': 'Known for its unique Mediterranean-like atmosphere, desert landscapes, and historic church.',
    'sachica': 'Known for its unique Mediterranean-like atmosphere, desert landscapes, and historic church.',
    'cucaita': 'A tranquil village surrounded by scenic mountains and traditional Boyacense countryside.',
    'chiquinquirá': 'The religious capital of Colombia, home to the majestic Basilica of Our Lady of Chiquinquirá and a center of spiritual pilgrimage.',
    'moniquirá': 'Known as the "Sweet Capital of Colombia" for its traditional bocadillo production, nestled in a lush green valley with a warm climate.',
    'garagoa': 'A vibrant town in the heart of the Tenza valley, surrounded by emerald mountains and famous for its traditional religious festivals.',
    'guateque': 'The birthplace of Enrique Olaya Herrera, this historic town in the Tenza valley is known for its beautiful colonial plaza and firework traditions.',
    'medellín': 'The "City of Eternal Spring," celebrated for its radical transformation and innovation. From the iconic Metrocable system to the vibrant street art of Comuna 13, Medellín offers a unique look at Colombian resilience and modern "Paisa" identity. The El Poblado district, specifically Parque Lleras and Provenza, serves as the primary hub for international gastronomy and social life.',
    'medellin': 'The "City of Eternal Spring," celebrated for its radical transformation and innovation. From the iconic Metrocable system to the vibrant street art of Comuna 13, Medellín offers a unique look at Colombian resilience and modern "Paisa" identity. The El Poblado district, specifically Parque Lleras and Provenza, serves as the primary hub for international gastronomy and social life.',
    'puerto boyacá': 'A major river port on the Magdalena River, offering a tropical atmosphere and acting as a vital link between the Andean highlands and the Caribbean plains.',
    'santa rosa de viterbo': 'A town of profound history and judicial tradition, featuring beautiful colonial architecture and serene highland landscapes.',
    'el cocuy': 'Gateway to the snow-capped Sierra Nevada del Cocuy, this charming colonial town features white-walled houses and emerald-green balconies.',
    'muzo': 'The "Emerald Capital of the World," located in a rugged mountain region famous for producing the world\'s finest green gemstones.',
    'ramiriquí': 'A historic center of agriculture and culture, known for its traditional corn-based gastronomy and its status as the cradle of the Southern Boyacá region.',
    'jenesano': 'Celebrated as one of Boyacá\'s most beautiful villages, famous for its lush gardens, fruit orchards, and perfectly preserved colonial charm.',
    'sora': 'A peaceful Andean municipality characterized by its rolling green hills, traditional potato farms, and quiet colonial atmosphere.',
    'soracá': 'A deeply religious town surrounded by fertile wheat fields and scenic mountains, offering stunning views of the central Boyacá landscape.',
    'sutamarchán': 'World-famous for its traditional "longaniza" sausages and its historic colonial architecture within a beautiful valley setting.',
    'tinjacá': 'Reputed to have one of the best climates in the world, this peaceful village is known for its tagua crafts and beautiful flowered streets.',
    'motavita': 'A quiet highland town with deep indigenous roots, offering panoramic views of the surrounding Andean valleys and traditional rural life.',
    'arcabuco': 'A scenic mountain pass town famous for its traditional "almojábanas" and its status as a gateway to the oak forests and the IGUAQUE sanctuary.',
    'belén': 'A historic and picturesque town known for its traditional leather handicrafts and its perfectly preserved colonial town square.',
    'boavita': 'Nestled on the edge of dramatic canyons, Boavita offers some of the most spectacular mountain landscapes and traditional highland agriculture in the region.',
    'boyacá': 'The historic namesake of the department, this peaceful colonial village preserves a quiet atmosphere and deep connection to the region\'s heritage.',
    'buenavista-boyaca': 'Located in the lush western range, Buenavista is known for its high-quality coffee production and its breathtaking panoramic viewpoints over the Andean valleys.',
    'chivatá': 'A traditional agricultural municipality characterized by its rolling green hills and its quiet, authentic Andean rural charm.',
    'chivor': 'Famed for its world-class emerald mines and the stunning La Esmeralda reservoir, Chivor is a place where rugged nature meets hidden treasures.',
    'cómbita': 'A land of champions and the heart of Colombia\'s cycling heritage, set against a backdrop of cold-climate farms and expansive highland plains.',
    'güicán': 'A stunning high-altitude gateway to the snow-capped Sierra Nevada del Cocuy, offering rugged trails and awe-inspiring mountain vistas.',
    'firavitoba': 'Home to one of the most magnificent neo-Gothic churches in the region, this town offers a peaceful heritage experience within its grand colonial plaza.',
    'gachantivá': 'An ecological paradise known for its hidden waterfalls, oak forests, and diverse flora, perfect for nature lovers and trekkers.',
    'miraflores': 'Located in the warm Lengupá province, Miraflores is famous for its citrus fruit orchards and its vibrant tropical Andean landscapes.',
    'samacá': 'A vital agricultural and industrial center, Samacá features a beautiful fertile valley known for its tradition of onion and coal production.',
    'tota': 'Set on the shores of Lake Tota, Colombia\'s largest lake, this town is famous for its cold-climate beauty and its scenic agricultural landscape.',
    'ventaquemada': 'The gastronomic gateway to Boyacá, world-famous for its traditional "arepas" and its proximity to the historic Puente de Boyacá.',
    'soatá': 'Known as the "City of Dates," Soatá is a vital highland hub featuring semi-dry tropical landscapes and the impressive backdrop of the Chicamocha canyon.',
    'turmequé': 'The birthplace of "Tejo," Colombia\'s national sport, this historic town preserves a deep cultural heritage and a vibrant colonial atmosphere.',
    'togüí': 'Nestled in a lush subtropical valley, Togüí is celebrated for its warm climate and its traditional production of coffee and panela.',
    'tenza': 'A master center of artisanal craftsmanship, Tenza is set within a breathtaking valley and is famous for its colorful basketry and colonial beauty.',
    'sotaquirá': 'A peaceful Andean municipality characterized by its fertile dairy lands and its status as a producer of some of the region\'s finest cheeses.',
    'siachoque': 'The "Potato Capital," where agricultural traditions run deep across its scenic highland plains and cold-climate rural landscapes.',
    'saboyá': 'A gateway to the majestic Andean oak forests, Saboyá offers a fresh mountain climate and beautiful ecological trails through high-altitude woods.',
    'nuevo colón': 'An agricultural jewel famous for its fruit orchards, where the landscape turns into a blossom-filled valley during the harvest seasons.',
    'otanche': 'A rugged and tropical emerald-mining town, offering untamed natural beauty and deep green valleys in the heart of the Boyacá western province.',
    'zetaquira': 'A thermal paradise nestled in the Lengupá valley, known for its medicinal hot springs and its lush coffee-growing hills.',
    'macanal': 'Perched high above the Chivor reservoir, Macanal offers some of the most dramatic water-and-mountain vistas in the entire department.',
    'cubará': 'A remote and spiritual territory bordering the Sarare region, home to the U\'wa indigenous people and the wild beauty of the eastern plains edge.',
    'chiscas': 'A high-altitude sanctuary on the edge of the Sierra Nevada, where rugged paramos and cold-climate endurance define the mountain landscape.',
    'coper': 'A vibrant tropical town in the western emerald region, surrounded by lush vegetation and the intense activity of gemstone discovery.',
    'betéitiva': 'A historic rural town known for its traditional stone bridge and its quiet, authentic Andean atmosphere among green rolling hills.',
    'almeida': 'A traditional Andean town set in the rugged Oriente province, Almeida is known for its peaceful rural atmosphere and scenic mountain views.',
    'berbeo': 'Nestled in the lush Lengupá region, Berbeo is a subtropical paradise celebrated for its coffee-growing hills and warm, welcoming climate.',
    'busbanzá': 'As Colombia\'s smallest municipality, Busbanzá offers a perfectly preserved colonial charm and a peaceful life centered around its historic town square.',
    'caldas': 'A land of scenic agricultural landscapes and rolling green hills, Caldas is a traditional highland town with a deep connection to its cold-climate farms.',
    'campohermoso': 'Set in the dramatic Lengupá River valley, Campohermoso is a place of wild green beauty, where high mountains meet warm tropical lowlands.',
    'cerinza': 'The capital of straw craftsmanship, Cerinza is famous for its intricate esparto basketry and its traditional Andean streets tucked between lush mountains.',
    'chinavita': 'A peaceful municipality in the Neira province, Chinavita is characterized by its fertile green valleys and scenic rolling highland hills.',
    'chíquiza': 'A high-altitude sanctuary bordering the paramo, Chíquiza preserves a traditional rural atmosphere and is a gateway to the region\'s unique Andean biodiversity.',
    'chita': 'Surrounded by majestic high-altitude mountains, Chita is a traditional northern hub known for its rugged landscapes and cold-climate rural heritage.',
    'chitaraque': 'A fertile valley town famous for its vast sugar cane plantations and its long tradition of producing high-quality panela.',
    'ciénega': 'A natural paradise on the edge of the Mamapacha paramo, Ciénega is known for its misty lagoons and its incredible ecological richness.',
    'corrales': 'Known as the "City of Light," Corrales is a beautiful colonial town that shines with its historic architecture and its famous light festivals.',
    'covarachía': 'Overlooking the majestic Chicamocha canyon, Covarachía offers dramatic dry-forest landscapes and steep, breathtaking Andean topography.',
    'cuítiva': 'A charming colonial village near the shores of Lake Tota, Cuítiva is a historic stop known for its beautiful church and gateway to the high-latitude lake.',
    'el espino': 'Situated at the foothills of the Sierra Nevada del Cocuy, El Espino offers stunning vistas of snow-capped peaks and traditional highland greenery.',
    'floresta': 'Known for its fossils and peaceful colonial atmosphere.',
    'gámeza': 'Famous for its historic "Piedras de Gámeza" and battle heritage.',
    'gameza': 'Famous for its historic "Piedras de Gámeza" and battle heritage.',
    'guacamayas': 'Renowned for its vibrant, colorful basketry crafts.',
    'guayatá': 'Iconic for its giant bread (Pan de Guayatá) and mountain views.',
    'boyacá-jericó': 'A high-altitude town set in dramatic Andean paramos.',
    'la capilla': 'A peaceful town in the Oriente province with scenic hills.',
    'la uvita': 'A traditional town in the Norte province with deep colonial roots.',
    'boyacá-la victoria': 'Located in the western emerald region with lush tropical landscapes.',
    'labranzagrande': 'A historic gateway to the eastern plains through the mountains.',
    'maripí': 'Another key emerald-mining town in the western province.',
    'mongua': 'Known for its indigenous heritage and the mysterious Laguna Negra.',
    'oicatá': 'A quiet agricultural town near Tunja with traditional rural charm.',
    'pachavita': 'A picturesque town in the Neira province with lush green valleys.',
    'páez': 'Set in the rugged Lengupá region with subtropical biodiversity.',
    'pajarito': 'The gateway to the Casanare plains, famous for its waterfalls.',
    'tuta': 'A traditional agricultural town in the Tundama province with 16th-century colonial origins.',
    'sativanorte': 'Set in the rugged mountains of the Norte province, offering dramatic Andean scenery.',
    'sativasur': 'A peaceful and authentic highlands town known for its hospitality and beautiful Andean landscapes.',
    'briceño': 'A high-altitude Andean town offering breathtaking mountain views and serene rural landscapes.',
    'buena vista': 'Famous for its "Mirador" status, offering spectacular views of the Western Province valleys.',
    'santana': 'A major panela production hub surrounded by lush sugar cane plantations.',
    'socha': 'A historic town with rugged paramos, pivotal in the 1819 independence campaign.',
    'socotá': 'The gateway to the pristine Pisba National Park, known for its high-altitude biodiversity.',
    'somondoco': 'Nestled in the green hills of the Oriente province, famous for its temperate climate scenery.',
    'susacón': 'A town showcasing dramatic Andean canyons and rugged mountain topography in the Norte province.',
    'sutatenza': 'Famous for its radio school heritage and its beautiful rolling green hills.',
    'tasco': 'An Andean town where coal mining heritage meets high-altitude paramo beauty.',
    'tibaná': 'A fertile agricultural hub known for its scenic valleys and traditional Andean atmosphere.',
    'tipacoque': 'Set in the unique dry tropical forest environment of the Chicamocha canyon region.',
    'tununguá': 'A lush tropical enclave in the Western province known for its citrus and coffee production.',
    'tutazá': 'A high-altitude town famous for its traditional pottery and religious heritage.',
    'tópaga': 'Known for its master stonemasons and its beautiful colonial art heritage.',
    'úmbita': 'A productive highland town featuring impressive agricultural terraces and Andean scenery.',
    'viracachá': 'A peaceful Andean municipality known for its beautiful temperate valleys and traditional hospitality.',
    'panqueba': 'A traditional Andean town with scenic highlands in the Norte province.',
    'pauna': 'A tropical hub in the western province known for emeralds and agriculture.',
    'paya': 'A historic town famous for the \"Termópilas de Paya\" battle site of the independence campaign.',
    'paz de río': 'An industrial town dominated by iron ore mines and dramatic canyon cliffs.',
    'pesca': 'A peaceful colonial town with a grand plaza and beautiful Andean rolling hills.',
    'pisba': 'Set in the wild paramos of the Pisba National Park, an iconic site of the Liberation Campaign.',
    'quípama': 'A lush tropical town in the western province, known for emerald extraction.',
    'rondón': 'A traditional municipality in the Márquez province with deep green Andean valleys.',
    'san eduardo': 'A warm-climate town in the Lengupá region known for coffee production.',
    'san josé de pare': 'A fertile town in the Ricaurte province famous for sugar cane and panela.',
    'san luis de gaceno': 'A tropical gateway to the eastern plains with rich biodiversity and rolling hills.',
    'san mateo': 'A traditional town in the Norte province with deep colonial roots and high-altitude paramos.',
    'san miguel de sema': 'Known for its dairy industry and proximity to the scenic Lake Fúquene.',
    'santa maría': 'A biodiversity hotspot in the Lengupá region with stunning waterfalls and dense forests.',
    'santa sofía': 'Famous for its impressive limestone caves and peaceful colonial atmosphere.',

    // Santander
    'bucaramanga': 'The "City of Parks," a vibrant urban center known for its beautiful green spaces, gastronomy, and modern shopping.',
    'san gil': 'Colombia\'s adventure capital, famous for white-water rafting, paragliding, and intense outdoor activities.',
    'barichara': 'Often called the most beautiful town in Colombia, famous for its yellow-stone colonial architecture and serene cobblestone streets.',
    'girón': 'A national monument town with white-walled colonial buildings and dark wood balconies, preserving a rich historical atmosphere.',
    'socorro': 'An important historical town where the "Comuneros" revolt began, featuring impressive stone-built colonial architecture.',
    'zapatoca': 'Known as the "city of the climate of silk" for its pleasant temperatures and serene mountain views.',
    'curití': 'A charming village famous for its traditional fique fiber crafts and beautiful stone streets.',
    'guadalupe': 'Home to "Las Gachas," a natural wonder of red rock riverbeds with multiple circular pools carved by water.',
    'barrancabermeja': 'A vibrant tropical river port on the Magdalena River, known for its sunsets and industrial heritage.',
    'floridablanca': 'A growing city famous for its "obleas" (traditional wafers) and its status as a sweet capital of the region.',
    'piedecuesta': 'Nestled in a lush green valley, this town is known for its traditional tobacco production and proximity to natural parks.',
    'málaga': 'The heart of García Rovira province, a colonial town surrounded by dramatic Andean mountain landscapes.',
    'vélez': 'World-famous for its guava paste (bocadillo) and its status as a capital of Colombian folk music.',
    'villanueva': 'A quiet colonial gem perched near the Chicamocha canyon, offering peaceful streets and incredible views.',
    'aratoca': 'The "Entry to the Chicamocha Canyon," famous for its traditional bread (Pan de Aratoca) and dramatic mountain vistas.',
    'barbosa': 'The "Golden Gate of Santander," a bustling commercial center and strategic gateway to the department.',
    'charalá': 'A historic town of immense importance in Colombian independence, known for the heroic Battle of Pienta and its giant Samán trees.',
    'cimitarra': 'A key agricultural hub in the Magdalena Medio region, surrounded by tropical landscapes and lush countryside.',
    'el carmen de chucurí': 'A mountain paradise famous for its world-class cacao production and rich tropical biodiversity.',
    'los santos': 'Perched on a scenic plateau, this town offers stunning canyon views and is known for its high-quality specialty coffee.',
    'oiba': 'The "Honey City of Colombia," renowned for its red-clay colonial architecture and proximity to lush forests.',
    'páramo': 'A gateway to nature, home to the spectacular Juan Curí waterfalls and lush subtropical landscapes.',
    'puente nacional': 'A historic colonial town where important independence movements took place, preserved with beautiful architecture.',
    'san vicente de chucurí': 'The "Cacao Capital of Colombia," a vibrant town surrounded by lush plantations and the Yariguíes National Park.',
    'suaita': 'A town of industry and nature, housing the ruins of Colombia\'s first textile factory and the grand Los Caballeros waterfall.',
    'valle de san josé': 'A charming colonial village world-famous for its traditional chorizos and preserved historical atmosphere.',
    'cepitá': 'A hidden gem deep within the Chicamocha Canyon, characterized by its arid beauty and colonial tranquility.',
    'pinchote': 'Birthplace of the heroine Antonia Santos, this peaceful colonial town preserves a rich historical heritage.',
    'santander-albania': 'A peaceful mountain town with stunning green landscapes and traditional colonial charm.',
    'betulia': 'Known for its scenic beauty and traditional coffee-growing heritage, surrounded by misty Andean peaks.',
    'bolívar': 'A historic and resilient town in southern Santander, known for its colonial legacy and mountain vistas.',
    'capitanejo': 'Perched on the banks of the Chicamocha River, known for its hot climate, goat breeding, and strategic mountain location.',
    'cerrito': 'An Andean town featuring high-altitude "páramo" landscapes and traditional stone architecture.',
    'contratación': 'A town with a unique history and heritage architecture, preserved with stories of resilience and community.',
    'florián': 'Home to the spectacular "Ventanas de Tisquizoque," a majestic waterfall exiting through a massive natural cave.',
    'gambita': 'Birthplace of musician Luis A. Calvo, a paradise of waterfalls including the grand Manto de la Virgen.',
    'jordán': 'A well-preserved "ghost town" at the bottom of the Chicamocha Canyon, offering a step back in time with its stone houses.',
    'la belleza': 'A hidden treasure known for its mystical limestone caves and lush, diverse agricultural landscapes.',
    'landázuri': 'A tropical paradise in the mountains, famous for its cacao plantations and misty forest trails.',
    'lebríja': 'The "Pineapple Capital of Colombia," a heights-positioned town known for its agricultural wealth and panoramic views.',
    'mogotes': 'A historic town near San Gil, renowned for its traditional handicrafts, scenic valleys, and colonial streets.',
    'puerto wilches': 'A strategic tropical port on the Magdalena River, surrounded by palm plantations and rich river ecosystems.',
    'santander-san andrés': 'The majestic gateway to García Rovira, featuring a landmark colonial church and a historic center perched atop dramatic Andean slopes.',
    'santander-sabana de torres': 'A strategic agricultural and industrial hub in the Magdalena Medio, known for its strategic location and tropical abundance.',
    'santander-rionegro': 'A warm-climate gem known for its cacao tradition, offering a vibrant community atmosphere nestled among lush green hills.',
    'santander-california': 'A historic high-altitude mining town with colonial architecture clinging to mist-covered peaks in the Soto Norte region.',
    'santander-vetas': 'One of the highest towns in Colombia, a traditional mining center surrounded by the ethereal beauty of the Santurbán páramo.',
    'santander-matanza': 'The colorful gateway to Soto Norte, preserving beautiful colonial facades amidst a landscape of lush green mountains.',
    'santander-suratá': 'An Andean paradise of cold climate and steep slopes, known for its historic mountain charm and misty landscapes.',
    'santander-tona': 'A serene high-altitude town with deep religious traditions, surrounded by the silence and mist of the Andean peaks.',
    'santander-simacota': 'Birthplace of the Comuneros movement, this peaceful village preserves historic stone houses and a legacy of Colombian independence.',
    'santander-sucre': 'A hidden mountain treasure in the Opón region, known for its rugged geography, rich biodiversity, and traditional rural life.',
    'santander-la paz': 'A peaceful southern destination famous for its traditional stone-paved streets and majestic mountain views.',
    'santander-el playón': 'A strategic mountain town on the northern highway, surrounded by dense tropical forests and misty green landscapes.',
    'santander-puerto parra': 'A biodiversity-rich river port in the Magdalena Medio, where the wetlands meet the tropical forest along the railway.',
    'santander-aguada': 'A tranquil jewel of the Vélez province, known for its peaceful colonial atmosphere and surrounding traditional farms.',
    'santander-cabrera': 'A charming colonial town in the Guanentá province, preserving its stone-paved streets and traditional Santander architecture.',
    'santander-carcasí': 'A remote mountain treasure in García Rovira, surrounded by dramatic cliffs and a peaceful Andean atmosphere.',
    'santander-charta': 'A lush mountain town in the Soto region, famous for its abundant water sources and beautiful green landscapes.',
    'santander-chipatá': 'A historic town in the Vélez province, featuring a unique stone-facade colonial church and a rich agricultural heritage.',
    'santander-concepción': 'A peaceful Andean village in García Rovira, known for its well-preserved colonial center and panoramic mountain views.',
    'santander-confines': 'A historic town in the Comuneros province, featuring a landmark colonial church and a legacy of Colombian independence history.',
    'santander-coromoro': 'A historic destination in the Guanentá province, where traditional colonial architecture meets lush river landscapes.',
    'santander-el guacamayo': 'A secluded mountain town in southern Santander, offering a dense tropical forest environment and rich biodiversity.',
    'santander-encino': 'A gateway to the Guanentá-Alto Fonce flora and fauna sanctuary, famous for its majestic oak forests and crystal-clear waters.',
    'santander-enciso': 'A warm-climate town in the García Rovira province, nestled in a fertile valley surrounded by lush tropical hills.',
    'santander-galán': 'A historic town named after Jose Antonio Galán, preserving a beautiful colonial church and traditional stone streets.',
    'santander-guaca': 'A destination of deep religious and colonial tradition, surrounded by majestic Andean peaks and traditional farms.',
    'santander-guapotá': 'A peaceful rural town in the Comuneros province, known for its coffee-growing traditions and rolling green hills.',
    'santander-guavatá': 'The "World Capital of Guava," a traditional town in the Vélez province surrounded by lush orchards and green mountains.',
    'santander-güepsa': 'A traditional town in the Vélez province, known for its sweet guava bocadillo production and colonial charm.',
    'santander-jesús maría': 'A peaceful colonial town in the Vélez province, featuring a landmark church and surrounded by rolling green agricultural hills.',
    'santander-macaravita': 'A majestic high-altitude town in García Rovira, offering dramatic views of Andean canyons and traditional stone streets.',
    'santander-molagavita': 'A scenic mountain destination in the García Rovira province, overlooking the spectacular landscapes of the Chicamocha region.',
    'santander-ocamonte': 'A charming colonial-style town in the Guanentá province, famous for its high-quality coffee and lush environmental beauty.',
    'santander-onzaga': 'A historic mountain town founded on ancestral lands, known for its colonial architecture and crystal-clear Andean streams.',
    'santander-palmar': 'A tranquil rural jewel in the Comuneros province, characterized by its namesake palm trees and peaceful community atmosphere.',
    'santander-san joaquín': 'The "Cold Pearl of Santander," a picturesque mountain town in Guanentá known for its mist-shrouded peaks and colonial church.',
    'santander-san miguel': 'A majestic remote town in García Rovira, nestled between dramatic limestone cliffs and lush hidden valleys.',
    'santander-santa bárbara': 'A high-altitude Soto treasure, where colonial houses sit amidst the clouds in a beautiful páramo-edge landscape.',
    'santander-san josé de miranda': 'A picturesque town in García Rovira, featuring a striking twin-towered church and a rich religious and agricultural heritage.',
    'santander-santa helena del opón': 'A remote paradise in the Opón mountains, surrounded by pristine tropical forests and spectacular hidden waterfalls.',
    'santander-san benito': 'A peaceful Vélez province town, preserving its traditional way of life among green hills and traditional sugar cane farms.',
    'santander-hato': 'A historic colonial town in the Comuneros province, known for its stone-paved streets and deep connection to the independence era.',
    'santander-chimá': 'A spiritual and historic town in the Comuneros province, site of the miraculous Virgin of the Rock and traditional architecture.',
    'santander-el peñón': 'A land of dramatic limestone formations and deep caves, offering extreme natural beauty and a traditional Santander mountain atmosphere.',

    // Antioquia
    'guatapé': 'A vibrant town famous for its incredibly colorful "zócalos" and the massive Peñol Rock offering 360-degree views.',
    'guatape': 'A vibrant town famous for its incredibly colorful "zócalos" and the massive Peñol Rock offering 360-degree views.',
    'jardín': 'One of Colombia\'s most beautiful towns, characterized by its flower-filled balconies and preserving colonial architecture.',
    'jardin': 'One of Colombia\'s most beautiful towns, characterized by its flower-filled balconies and preserving colonial architecture.',
    'jericó': 'The birthplace of Mother Laura, famous for its traditional leather "carriel" bags and stunning mountain scenery.',
    'jerico': 'The birthplace of Mother Laura, famous for its traditional leather "carriel" bags and stunning mountain scenery.',
    'santafé de antioquia': 'The historical capital of the department, featuring remarkable colonial architecture and the iconic Bridge of the West.',
    'santafe de antioquia': 'The historical capital of the department, featuring remarkable colonial architecture and the iconic Bridge of the West.',
    'santa rosa de osos': 'A high-altitude town known for its dairy traditions and the "Cathedral of the North."',
    'támesis': 'An ecological paradise known for its pre-Columbian petroglyphs and diverse hiking trails.',
    'tamesis': 'An ecological paradise known for its pre-Columbian petroglyphs and diverse hiking trails.',
    'rionegro': 'A historical industrial hub and the gateway to the beautiful San Nicolás valley.',
    'envigado': 'A traditional town that maintains a small-town feel within the metro area, famous for its gastronomy and festivals.',
    'sabaneta': 'The smallest municipality in Colombia, known for its vibrant town square and traditional buñuelos.',
    'itagüí': 'An industrial city known for its cultural centers and vibrant street murals.',
    'itagui': 'An industrial city known for its cultural centers and vibrant street murals.',
    'la ceja': 'A peaceful valley town famous for its flower exports and its strong cycling culture.',
    'el carmen de viboral': 'Famous worldwide for its unique, hand-painted ceramic traditions and artistic streets.',

    // Bolívar
    'cartagena': 'A UNESCO World Heritage site and the crown jewel of the Caribbean. The "Walled City" (Centro Histórico) and Getsemaní are living museums of Spanish colonial power, featuring the massive Castillo de San Felipe de Barajas fortress. Modern Cartagena thrives in Bocagrande, a peninsula of high-rise hotels that offers a vibrant contrast to the historic fortifications.',
    'cartagena de indias': 'A UNESCO World Heritage site and the crown jewel of the Caribbean. The "Walled City" (Centro Histórico) and Getsemaní are living museums of Spanish colonial power, featuring the massive Castillo de San Felipe de Barajas fortress. Modern Cartagena thrives in Bocagrande, a peninsula of high-rise hotels that offers a vibrant contrast to the historic fortifications.',
    'mompós': 'Santa Cruz de Mompós is a UNESCO World Heritage site frozen in time, famous for its colonial architecture and its intricate filigree jewelry.',
    'san jacinto': 'San Jacinto is a cultural hub in the Montes de María, world-renowned for its artisanal hammocks, traditional Gaita music, and rich indigenous heritage.',
    'magangué': 'Known as the "City of Rivers," Magangué is a major commercial port at the confluence of the Magdalena, Cauca, and San Jorge rivers.',
    'el carmen de bolívar': 'Located in the heart of the Montes de María, El Carmen de Bolívar is an agricultural center famous for its cultural resilience and delicious local gastronomy.',
    'turbaco': 'A scenic retreat near Cartagena, Turbaco is known for its cool climate, botanical gardens, and prehistoric mud volcanoes.',
    'san juan nepomuceno': 'Home to the Los Colorados Sanctuary, San Juan Nepomuceno offers a unique glimpse into the tropical dry forest and rich local traditions.',
    'santa rosa del sur': 'Nestled in the high mountains of the Serranía de San Lucas, Santa Rosa del Sur is a vibrant town known for its emerald mines and stunning mountain landscapes.',
    'mahates': 'Mahates is the gateway to San Basilio de Palenque, the first free town in the Americas and a UNESCO Intangible Cultural Heritage site for its unique language and traditions.',
    'arjona': 'Arjona is an agricultural powerhouse famous for its traditional "Bollo Limón" and vibrant celebrations of Caribbean culture.',
    'maría la baja': 'Surrounded by fertile plains and scenic marshlands, María la Baja is a major rice and African palm producer with a rich African-descendant heritage.',
    'bolivar-villanueva': 'Villanueva is a tranquil town in the lower Bolívar plains, known for its colonial church and being a center for traditional livestock and agricultural trade.',
    'bolivar-santa rosa': 'Santa Rosa, known for its warm Caribbean atmosphere and colonial influence, is a peaceful gateway to the northern plains of Bolívar.',
    'clemencia': 'Clemencia is a charming agricultural town near the Caribbean coast, known for its lush vegetation and traditional rural hospitality.',
    'bolivar-calamar': 'Strategically located where the Canal del Dique meets the Magdalena River, Calamar is a historic river port with deep ties to Colombian transportation history.',
    'san estanislao': 'Also known as Arenal, San Estanislao is a vibrant river town with a rich cultural heritage and traditional religious celebrations.',
    'el guamo': 'Nestled in the Montes de María, El Guamo is an agricultural center known for its diverse crops and its resilient, welcoming community.',
    'bolivar-córdoba': 'Córdoba is a historic town on the banks of the Magdalena River, celebrated for its colonial church and its importance in regional trade.',
    'soplaviento': 'Soplaviento sits gracefully along the Canal del Dique, where fishing and river traditions define the local way of life and culture.',
    'bolivar-san cristóbal': 'A picturesque town on the Canal del Dique, San Cristóbal is known for its traditional fishing economy and its scenic water landscapes.',
    'zambrano': 'Zambrano is a major river port on the Magdalena, offering stunning sunrise views and serving as a key gateway to the lower Bolívar plains.',
    'pinillos': 'Located where the Magdalena River branches into the Mompós depression, Pinillos is a land of water and history with a unique riverine identity.',
    'tiquisio': 'Tiquisio is a vibrant town in southern Bolívar, known for its rich mining heritage and its strategic location in the fertile San Jorge river basin.',
    'achí': 'Achí is a picturesque river municipality in the Mojana region, where the Cauca River defines the local culture, fishing traditions, and fertile agricultural life.',
    'altos del rosario': 'Altos del Rosario is a peaceful town in the heart of Bolívar, known for its traditional colonial architecture and its role as a quiet agricultural center.',
    'barranco de loba': 'Key to the Loba region, Barranco de Loba is a historic river port on the Magdalena, serving as a vital hub for trade and traditional river transportation.',
    'cantagallo': 'Cantagallo is the southernmost municipality of Bolívar, where the Magdalena River provides a stunning backdrop for its agricultural and riverfront activities.',
    'hatillo de loba': 'Hatillo de Loba is an amphibious town deeply connected to the river, known for its resilient spirit and the unique water-based lifestyle of its inhabitants.',
    'montecristo': 'Montecristo is nestled in the foothills of the Serranía de San Lucas, offering a rugged landscape rich in biodiversity and traditional mining history.',
    'bolivar-morales': 'Morales is a bustling river port and agricultural center in southern Bolívar, acting as a gateway to the diverse landscapes of the Magdalena valley.',
    'norosí': 'Norosí is a historic mining town set against the beautiful backdrop of southern Bolívar\'s mountains, known for its hardworking community and natural wealth.',
    'regidor': 'Regidor is a tranquil town on the banks of the Magdalena River, where time seems to slow down and the local life follows the rhythm of the river.',
    'río viejo': 'Río Viejo is located where multiple river channels meet, creating a lush and fertile landscape that supports a vibrant fishing and farming community.',
    'bolivar-san jacinto del cauca': 'San Jacinto del Cauca is a remote and beautiful riverside town, where the Cauca River shapes the lush landscapes and the traditional rural way of life.',
    'san martín de loba': 'San Martín de Loba is the heart of the Loba region, a historic river port on the Magdalena with a vibrant culture deeply rooted in fishing and traditional music.',
    'santa catalina': 'Famous for the El Totumo mud volcano, Santa Catalina offers a unique combination of volcanic landscapes and beautiful Caribbean coastline in northern Bolívar.',
    'bolivar-san pablo': 'San Pablo is a vital river port in southern Bolívar, where the Magdalena River provides a majestic backdrop for its bustling agricultural and commercial activities.',
    'bolivar-san fernando': 'San Fernando is a peaceful town in the Mompós depression, surrounded by serene river channels and known for its traditional amphibious lifestyle.',
    'simití': 'Simití is the jewel of southern Bolívar, famously situated on a beautiful lagoon and rich in colonial history, reflected in its stunning historic church.',
    'talaigua nuevo': 'Talaigua Nuevo is a charming riverside town where the traditions of the Mompós depression are preserved in its peaceful streets and riverfront life.',
    'turbaná': 'Turbaná is a gateway to northern Bolívar, offering a warm tropical climate and a lively community centered around its historic town plaza.',
    'arroyohondo': 'Nestled in the green hills of northern Bolívar, Arroyohondo is a peaceful agricultural town that offers a quiet escape into the department\'s rural interior.',
    'cicuco': 'Cicuco is defined by the intricate web of Magdalena River channels that surround it, creating a unique and fertile amphibious landscape.',
    'margarita': 'Margarita is a tranquil river municipality in the heart of the Mompós depression, where life follows the gentle rhythm of the Magdalena River.',
    'arenal': 'Arenal is a historic river town known for its traditional colonial architecture and its peaceful setting along the banks of the Magdalena.',
    'bolivar-arenal': 'Arenal is a historic river town known for its traditional colonial architecture and its peaceful setting along the banks of the Magdalena.',
    'bolivar-el peñón': 'El Peñón is a scenic mountain town in the Serranía de San Lucas, offering rugged landscapes and a rich tradition of highland agriculture.',
    'san pablo de borbur': 'Known for its emerald mines, San Pablo de Borbur is a vibrant town set against the dramatic mountain landscapes of the western range.',
    'bolivar-san pablo de borbur': 'Known for its emerald mines, San Pablo de Borbur is a vibrant town set against the dramatic mountain landscapes of the western range.'
};

export function getCityOverview(cityName: string, defaultDescription?: string, departmentName?: string): string {
    const name = cityName.toLowerCase();
    const dept = departmentName?.toLowerCase();

    // Check for specific department-city mapping first to handle name collisions
    if (dept) {
        const specificKey = `${dept}-${name}`;
        if (cityOverviews[specificKey]) return cityOverviews[specificKey];
    }

    // Check for direct matches
    if (cityOverviews[name]) return cityOverviews[name];

    // Check for partial matches
    for (const [key, value] of Object.entries(cityOverviews)) {
        if (name === key || name.includes(key) || key.includes(name)) {
            return value;
        }
    }

    return defaultDescription || `Discover the beauty and culture of ${cityName}, a unique destination in Colombia.`;
}
