import { getAssetPath } from './utils';

export const cityImages: Record<string, string> = {
    'bucaramanga': '/images/city-bucaramanga.png',
    'manizales': '/images/city-manizales.png',
    'pereira': '/images/city-pereira.png',
    'armenia': '/images/city-armenia.png',
    'cúcuta': '/images/city-cucuta.png',
    'cucuta': '/images/city-cucuta.png',
    'ibagué': '/images/city-ibague.png',
    'ibague': '/images/city-ibague.png',
    'neiva': '/images/city_neiva.png',
    'pasto': '/images/city_pasto.png',
    'villavicencio': '/images/city_villavicencio.png',
    'popayán': '/images/city_popayan.png',
    'popayan': '/images/city_popayan.png',
    'popay': '/images/city_popayan.png',
    'valledupar': '/images/city_valledupar.png',
    'montería': '/images/city_monteria.png',
    'monteria': '/images/city_monteria.png',
    'monter': '/images/city_monteria.png',
    'tunja': '/images/city_tunja.png',
    'riohacha': '/images/city_riohacha.png',
    'quibdó': '/images/city_quibdo.png',
    'quibdo': '/images/city_quibdo.png',
    'quibd': '/images/city_quibdo.png',
    'leticia': '/images/city_leticia.png',
    'florencia': '/images/city_florencia.png',
    'yopal': '/images/city_yopal.png',
    'arauca': '/images/city_arauca.png',
    'sincelejo': '/images/city_sincelejo.png',
    'mocoa': '/images/city_mocoa.png',
    'inírida': '/images/city_inirida.png',
    'inirida': '/images/city_inirida.png',
    'mitu': '/images/city_mitu.png',
    'mitú': '/images/city_mitu.png',
    'buenavista': '/images/city_buenavista.png',
    'circasia': '/images/city_circasia.png',
    'córdoba': '/images/city_cordoba.png',
    'cordoba': '/images/city_cordoba.png',
    'filandia': '/images/city_filandia.png',
    'la tebaida': '/images/city_la_tebaida.png',
    'montenegro': '/images/city_montenegro.png',
    'pijao': '/images/city_pijao.png',
    'quimbaya': '/images/city_quimbaya.png',
    'salento': '/images/city_salento.png',
    'calarcá': '/images/city_calarca.png',
    'calarca': '/images/city_calarca.png',
    'génova': '/images/city_genova.png',
    'genova': '/images/city_genova.png',
    'mirití paraná': '/images/city_miriti_parana.png',
    'miriti paraná': '/images/city_miriti_parana.png',
    'mirití parana': '/images/city_miriti_parana.png',
    'miriti parana': '/images/city_miriti_parana.png',
    'puerto nariño': '/images/city_puerto_narino.png',
    'puerto narino': '/images/city_puerto_narino.png',
    'el encanto': '/images/city_el_encanto.png',
    'la chorrera': '/images/city_la_chorrera.png',
    'la pedrera': '/images/city_la_pedrera.png',
    'la victoria': '/images/city_la_victoria.png',
    'puerto arica': '/images/city_puerto_arica.png',
    'puerto santander': '/images/city_puerto_santander.png',
    'tarapacá': '/images/city_tarapaca.png',
    'tarapaca': '/images/city_tarapaca.png',
    'puerto alegría': '/images/city_puerto_alegria.png',
    'puerto alegria': '/images/city_puerto_alegria.png',
    'puerto carreño': '/images/city_puerto_carreno.png',
    'puerto carreno': '/images/city_puerto_carreno.png',
    'guatapé': '/images/city_guatape.png',
    'guatape': '/images/city_guatape.png',
    'jardín': '/images/city_jardin.png',
    'jardin': '/images/city_jardin.png',
    'jericó': '/images/city_jerico.png',
    'jerico': '/images/city_jerico.png',
    'santafé de antioquia': '/images/city_santafe_antioquia.png',
    'santafe de antioquia': '/images/city_santafe_antioquia.png',
    'santa rosa de osos': '/images/city_santa_rosa_osos.png',
    'támesis': '/images/city_tamesis.png',
    'tamesis': '/images/city_tamesis.png',
    'rionegro': '/images/city_rionegro.png',
    'envigado': '/images/city_envigado.png',
    'sabaneta': '/images/city_sabaneta.png',
    'itagüí': '/images/city_itagui.png',
    'itagui': '/images/city_itagui.png',
    'la ceja': '/images/city_la_ceja.png',
    'el carmen de viboral': '/images/city_el_carmen_viboral.png',
    'bogotá': '/images/city-bogota.png',
    'bogota': '/images/city-bogota.png',
    'bogot': '/images/city-bogota.png',
    'santafé de bogotá': '/images/city-bogota.png',
    'santafe de bogota': '/images/city-bogota.png',
    'medellín': '/images/city-medellin.png',
    'medellin': '/images/city-medellin.png',
    'medell': '/images/city-medellin.png',
    'cali': '/images/city-cali.png',
    'santiago de cali': '/images/city-cali.png',
    'barranquilla': '/images/city-barranquilla.png',
    'santa marta': '/images/city-santa-marta.png',
    'cartagena': '/images/city_cartagena.png',
    'cartagena de indias': '/images/city_cartagena.png',
    'san andrés': '/images/city-san-andres.png',
    'san andres': '/images/city-san-andres.png',
    'san andr': '/images/city-san-andres.png'
};

export function getCityImage(cityName: string): string {
    const name = cityName.toLowerCase();

    for (const [key, value] of Object.entries(cityImages)) {
        if (name.includes(key) || key.includes(name)) {
            return getAssetPath(value);
        }
    }

    if (cityImages[name]) return getAssetPath(cityImages[name]);

    return `https://source.unsplash.com/800x600/?colombia,${cityName}`;
}
