import { getAssetPath } from './utils';

export const cityImages: Record<string, string> = {
    'cartagena': '/images/city_cartagena.png',
    'cartagena de indias': '/images/city_cartagena.png',
    'mompós': '/images/city_mompos.png',
    'mompos': '/images/city_mompos.png',
    'santa cruz de mompós': '/images/city_mompos.png',
    'san jacinto': '/images/city_san_jacinto.png',
    'magangué': '/images/city_magangue.png',
    'magangue': '/images/city_magangue.png',
    'el carmen de bolívar': '/images/city_el_carmen_bolivar.png',
    'turbaco': '/images/city_turbaco.png',
    'san juan nepomuceno': '/images/city_san_juan_nepomuceno.png',
    'santa rosa del sur': '/images/city_santa_rosa_del_sur.png',
    'mahates': '/images/city_mahates.png',
    'arjona': '/images/city_arjona.png',
    'maría la baja': '/images/city_maria_la_baja.png',
    'bolivar-villanueva': '/images/city_villanueva_bolivar.png',
    'bolivar-santa rosa': '/images/city_santa_rosa_bolivar.png',
    'clemencia': '/images/city_clemencia.png',
    'bolivar-calamar': '/images/city_calamar_bolivar.png',
    'san estanislao': '/images/city_san_estanislao.png',
    'el guamo': '/images/city_el_guamo.png',
    'bolivar-córdoba': '/images/city_cordoba_bolivar.png',
    'soplaviento': '/images/city_soplaviento.png',
    'bolivar-san cristóbal': '/images/city_san_cristobal_bolivar.png',
    'zambrano': '/images/city_zambrano.png',
    'pinillos': '/images/city_pinillos.png',
    'tiquisio': '/images/city_tiquisio.png',
    'santander-bucaramanga': '/images/city_bucaramanga.png',
    'manizales': '/images/city-manizales.png',
    'pereira': '/images/city-pereira.png',
    'armenia': '/images/city-armenia.png',
    'cúcuta': '/images/city-cucuta.png',
    'cucuta': '/images/city-cucuta.png',
    'ibagué': '/images/city-ibague.png',
    'ibague': '/images/city-ibague.png',
    'neiva': '/images/city_neiva.png',
    'pasto': '/images/city_pasto.png',
    'villavicencio': '/images/city_villavicencio.png',
    'popayán': '/images/city_popayan.png',
    'popayan': '/images/city_popayan.png',
    'popay': '/images/city_popayan.png',
    'valledupar': '/images/city_valledupar.png',
    'montería': '/images/city_monteria.png',
    'monteria': '/images/city_monteria.png',
    'monter': '/images/city_monteria.png',
    'tunja': '/images/city_tunja.png',
    'riohacha': '/images/city_riohacha.png',
    'quibdó': '/images/city_quibdo.png',
    'quibdo': '/images/city_quibdo.png',
    'quibd': '/images/city_quibdo.png',
    'leticia': '/images/city_leticia.png',
    'florencia': '/images/city_florencia.png',
    'yopal': '/images/city_yopal.png',
    'arauca': '/images/city_arauca.png',
    'sincelejo': '/images/city_sincelejo.png',
    'mocoa': '/images/city_mocoa.png',
    'inírida': '/images/city_inirida.png',
    'inirida': '/images/city_inirida.png',
    'mitu': '/images/city_mitu.png',
    'mitú': '/images/city_mitu.png',
    'buenavista': '/images/city_buenavista.png',
    'circasia': '/images/city_circasia.png',
    'córdoba': '/images/city_cordoba.png',
    'cordoba': '/images/city_cordoba.png',
    'filandia': '/images/city_filandia.png',
    'la tebaida': '/images/city_la_tebaida.png',
    'montenegro': '/images/city_montenegro.png',
    'pijao': '/images/city_pijao.png',
    'quimbaya': '/images/city_quimbaya.png',
    'salento': '/images/city_salento.png',
    'calarcá': '/images/city_calarca.png',
    'calarca': '/images/city_calarca.png',
    'génova': '/images/city_genova.png',
    'genova': '/images/city_genova.png',
    'mirití paraná': '/images/city_miriti_parana.png',
    'miriti paraná': '/images/city_miriti_parana.png',
    'mirití parana': '/images/city_miriti_parana.png',
    'miriti parana': '/images/city_miriti_parana.png',
    'puerto nariño': '/images/city_puerto_narino.png',
    'puerto narino': '/images/city_puerto_narino.png',
    'el encanto': '/images/city_el_encanto.png',
    'la chorrera': '/images/city_la_chorrera.png',
    'la pedrera': '/images/city_la_pedrera.png',
    'la victoria': '/images/city_la_victoria.png',
    'puerto arica': '/images/city_puerto_arica.png',
    'puerto santander': '/images/city_puerto_santander.png',
    'tarapacá': '/images/city_tarapaca.png',
    'tarapaca': '/images/city_tarapaca.png',
    'puerto alegría': '/images/city_puerto_alegria.png',
    'puerto alegria': '/images/city_puerto_alegria.png',
    'puerto carreño': '/images/city_puerto_carreno.png',
    'puerto carreno': '/images/city_puerto_carreno.png',
    'guatapé': '/images/city_guatape.png',
    'guatape': '/images/city_guatape.png',
    'jardín': '/images/city_jardin.png',
    'jardin': '/images/city_jardin.png',
    'jericó': '/images/city_jerico.png',
    'jerico': '/images/city_jerico.png',
    'santafé de antioquia': '/images/city_santafe_antioquia.png',
    'santafe de antioquia': '/images/city_santafe_antioquia.png',
    'santa rosa de osos': '/images/city_santa_rosa_osos.png',
    'támesis': '/images/city_tamesis.png',
    'tamesis': '/images/city_tamesis.png',
    'rionegro': '/images/city_rionegro.png',
    'envigado': '/images/city_envigado.png',
    'sabaneta': '/images/city_sabaneta.png',
    'itagüí': '/images/city_itagui.png',
    'itagui': '/images/city_itagui.png',
    'la ceja': '/images/city_la_ceja.png',
    'el carmen de viboral': '/images/city_el_carmen_viboral.png',
    'villa de leyva': '/images/city_villa_de_leyva.png',
    'paipa': '/images/city_paipa.png',
    'monguí': '/images/city_mongui.png',
    'mongui': '/images/city_mongui.png',
    'ráquira': '/images/city_raquira.png',
    'raquira': '/images/city_raquira.png',
    'sogamoso': '/images/city_sogamoso.png',
    'duitama': '/images/city_duitama.png',
    'iza': '/images/city_iza.png',
    'nobsa': '/images/city_nobsa.png',
    'aquitania': '/images/city_aquitania.png',
    'tibasosa': '/images/city_tibasosa.png',
    'sáchica': '/images/city_sachica.png',
    'sachica': '/images/city_sachica.png',
    'cucaita': '/images/city_cucaita.png',
    'san gil': '/images/city_san_gil.png',
    'barichara': '/images/city_barichara.png',
    'girón': '/images/city_giron.png',
    'giron': '/images/city_giron.png',
    'socorro': '/images/city_socorro.png',
    'zapatoca': '/images/city_zapatoca.png',
    'curití': '/images/city_curiti.png',
    'curiti': '/images/city_curiti.png',
    'guadalupe': '/images/city_guadalupe.png',
    'barrancabermeja': '/images/city_barrancabermeja.png',
    'floridablanca': '/images/city_floridablanca.png',
    'piedecuesta': '/images/city_piedecuesta.png',
    'málaga': '/images/city_malaga.png',
    'malaga': '/images/city_malaga.png',
    'vélez': '/images/city_velez.png',
    'velez': '/images/city_velez.png',
    'villanueva': '/images/city_villanueva.png',
    'aratoca': '/images/city_aratoca.png',
    'barbosa': '/images/city_barbosa.png',
    'charalá': '/images/city_charala.png',
    'charala': '/images/city_charala.png',
    'cimitarra': '/images/city_cimitarra.png',
    'el carmen de chucurí': '/images/city_el_carmen_de_chucuri.png',
    'el carmen de chucuri': '/images/city_el_carmen_de_chucuri.png',
    'los santos': '/images/city_los_santos.png',
    'oiba': '/images/city_oiba.png',
    'páramo': '/images/city_paramo.png',
    'paramo': '/images/city_paramo.png',
    'puente nacional': '/images/city_puente_nacional.png',
    'san vicente de chucurí': '/images/city_san_vicente_de_chucuri.png',
    'san vicente de chucuri': '/images/city_san_vicente_de_chucuri.png',
    'suaita': '/images/city_suaita.png',
    'valle de san josé': '/images/city_valle_de_san_jose.png',
    'valle de san jose': '/images/city_valle_de_san_jose.png',
    'cepitá': '/images/city_cepita.png',
    'cepita': '/images/city_cepita.png',
    'pinchote': '/images/city_pinchote.png',
    'santander-albania': '/images/city_albania.png',
    'betulia': '/images/city_betulia.png',
    'bolívar': '/images/city_bolivar.png',
    'bolivar': '/images/city_bolivar.png',
    'capitanejo': '/images/city_capitanejo.png',
    'cerrito': '/images/city_cerrito.png',
    'contratación': '/images/city_contratacion.png',
    'contratacion': '/images/city_contratacion.png',
    'florián': '/images/city_florian.png',
    'florian': '/images/city_florian.png',
    'gambita': '/images/city_gambita.png',
    'jordán': '/images/city_jordan.png',
    'jordan': '/images/city_jordan.png',
    'la belleza': '/images/city_la_belleza.png',
    'landázuri': '/images/city_landazuri.png',
    'landazuri': '/images/city_landazuri.png',
    'lebríja': '/images/city_lebrija.png',
    'lebrija': '/images/city_lebrija.png',
    'mogotes': '/images/city_mogotes.png',
    'puerto wilches': '/images/city_puerto_wilches.png',
    'santander-san andrés': '/images/city_san_andres_santander.png',
    'santander-sabana de torres': '/images/city_sabana_torres.png',
    'santander-rionegro': '/images/city_rionegro_santander.png',
    'santander-california': '/images/city_california.png',
    'santander-vetas': '/images/city_vetas.png',
    'santander-matanza': '/images/city_matanza.png',
    'santander-suratá': '/images/city_surata.png',
    'santander-tona': '/images/city_tona.png',
    'santander-simacota': '/images/city_simacota.png',
    'santander-sucre': '/images/city_sucre_santander.png',
    'santander-la paz': '/images/city_la_paz_santander.png',
    'santander-el playón': '/images/city_el_playon.png',
    'santander-puerto parra': '/images/city_puerto_parra.png',
    'santander-aguada': '/images/city_aguada.png',
    'santander-cabrera': '/images/city_cabrera.png',
    'santander-carcasí': '/images/city_carcasi.png',
    'santander-charta': '/images/city_charta.png',
    'santander-chipatá': '/images/city_chipata.png',
    'santander-concepción': '/images/city_concepcion.png',
    'santander-confines': '/images/city_confines.png',
    'santander-coromoro': '/images/city_coromoro.png',
    'santander-el guacamayo': '/images/city_el_guacamayo.png',
    'santander-encino': '/images/city_encino.png',
    'santander-enciso': '/images/city_enciso.png',
    'santander-galán': '/images/city_galan.png',
    'santander-guaca': '/images/city_guaca.png',
    'santander-guapotá': '/images/city_guapota.png',
    'santander-guavatá': '/images/city_guavata.png',
    'santander-güepsa': '/images/city_guepsa.png',
    'santander-jesús maría': '/images/city_jesus_maria.png',
    'santander-macaravita': '/images/city_macaravita.png',
    'santander-molagavita': '/images/city_molagavita.png',
    'santander-ocamonte': '/images/city_ocamonte.png',
    'santander-onzaga': '/images/city_onzaga.png',
    'santander-palmar': '/images/city_palmar.png',
    'santander-san joaquín': '/images/city_san_joaquin.png',
    'santander-san miguel': '/images/city_san_miguel.png',
    'santander-santa bárbara': '/images/city_santa_barbara.png',
    'santander-san josé de miranda': '/images/city_san_jose_de_miranda.png',
    'santander-santa helena del opón': '/images/city_santa_helena_del_opon.png',
    'santander-san benito': '/images/city_san_benito.png',
    'santander-hato': '/images/city_hato.png',
    'santander-chimá': '/images/city_chima.png',
    'santander-el peñón': '/images/city_el_penon.png',
    'bogotá': '/images/city-bogota.png',
    'bogota': '/images/city-bogota.png',
    'bogot': '/images/city-bogota.png',
    'santafé de bogotá': '/images/city-bogota.png',
    'santafe de bogota': '/images/city-bogota.png',
    'medellín': '/images/city-medellin.png',
    'medellin': '/images/city-medellin.png',
    'medell': '/images/city-medellin.png',
    'cali': '/images/city-cali.png',
    'santiago de cali': '/images/city-cali.png',
    'barranquilla': '/images/city-barranquilla.png',
    'santa marta': '/images/city-santa-marta.png',
    'san andrés': '/images/city-san-andres.png',
    'san andres': '/images/city-san-andres.png',
    'san andr': '/images/city-san-andres.png'
};

export function getCityImage(cityName: string, departmentName?: string): string {
    const name = cityName.toLowerCase();
    const dept = departmentName?.toLowerCase();

    // Check for specific department-city mapping first to handle name collisions
    if (dept) {
        const specificKey = `${dept}-${name}`;
        if (cityImages[specificKey]) return getAssetPath(cityImages[specificKey]);
    }

    for (const [key, value] of Object.entries(cityImages)) {
        if (name === key || name.includes(key) || key.includes(name)) {
            return getAssetPath(value);
        }
    }

    if (cityImages[name]) return getAssetPath(cityImages[name]);

    return `https://source.unsplash.com/800x600/?colombia,${cityName}`;
}

export const cityOverviews: Record<string, string> = {
    // Boyacá
    'villa de leyva': 'Famous for its massive cobblestone plaza and beautifully preserved white colonial buildings.',
    'tunja': 'The capital of Boyacá and the highest capital city in Colombia. It features a rich colonial heritage, historic churches, and was built on the site of the ancient Muisca capital Hunza.',
    'paipa': 'Known for the serene Lake Sochagota and its relaxing medicinal thermal springs.',
    'monguí': 'A "Pueblo Patrimonio" of Colombia, famous for its historic stone bridge and hand-stitched soccer ball industry.',
    'raquira': 'The craft capital of Boyacá, famous for its extremely colorful pottery shops and colonial charm.',
    'ráquira': 'The craft capital of Boyacá, famous for its extremely colorful pottery shops and colonial charm.',
    'sogamoso': 'Home to the Sun Temple of the Muiscas, an important site of indigenous heritage.',
    'duitama': 'Features the "Pueblito Boyacense," a charming area representing the architecture of the region\'s diverse towns.',
    'iza': 'A peaceful colonial town known for its green hills and traditional dessert market.',
    'nobsa': 'Renowned for its high-quality wool crafts, especially traditional ruanas and blankets.',
    'aquitania': 'Offers stunning panoramic views of Lake Tota, the largest lake in Colombia.',
    'tibasosa': 'A picturesque colonial town famous for its beautiful gardens and Feijoa fruit products.',
    'sáchica': 'Known for its unique Mediterranean-like atmosphere, desert landscapes, and historic church.',
    'sachica': 'Known for its unique Mediterranean-like atmosphere, desert landscapes, and historic church.',
    'cucaita': 'A tranquil village surrounded by scenic mountains and traditional Boyacense countryside.',

    // Santander
    'bucaramanga': 'The "City of Parks," a vibrant urban center known for its beautiful green spaces, gastronomy, and modern shopping.',
    'san gil': 'Colombia\'s adventure capital, famous for white-water rafting, paragliding, and intense outdoor activities.',
    'barichara': 'Often called the most beautiful town in Colombia, famous for its yellow-stone colonial architecture and serene cobblestone streets.',
    'girón': 'A national monument town with white-walled colonial buildings and dark wood balconies, preserving a rich historical atmosphere.',
    'socorro': 'An important historical town where the "Comuneros" revolt began, featuring impressive stone-built colonial architecture.',
    'zapatoca': 'Known as the "city of the climate of silk" for its pleasant temperatures and serene mountain views.',
    'curití': 'A charming village famous for its traditional fique fiber crafts and beautiful stone streets.',
    'guadalupe': 'Home to "Las Gachas," a natural wonder of red rock riverbeds with multiple circular pools carved by water.',
    'barrancabermeja': 'A vibrant tropical river port on the Magdalena River, known for its sunsets and industrial heritage.',
    'floridablanca': 'A growing city famous for its "obleas" (traditional wafers) and its status as a sweet capital of the region.',
    'piedecuesta': 'Nestled in a lush green valley, this town is known for its traditional tobacco production and proximity to natural parks.',
    'málaga': 'The heart of García Rovira province, a colonial town surrounded by dramatic Andean mountain landscapes.',
    'vélez': 'World-famous for its guava paste (bocadillo) and its status as a capital of Colombian folk music.',
    'villanueva': 'A quiet colonial gem perched near the Chicamocha canyon, offering peaceful streets and incredible views.',
    'aratoca': 'The "Entry to the Chicamocha Canyon," famous for its traditional bread (Pan de Aratoca) and dramatic mountain vistas.',
    'barbosa': 'The "Golden Gate of Santander," a bustling commercial center and strategic gateway to the department.',
    'charalá': 'A historic town of immense importance in Colombian independence, known for the heroic Battle of Pienta and its giant Samán trees.',
    'cimitarra': 'A key agricultural hub in the Magdalena Medio region, surrounded by tropical landscapes and lush countryside.',
    'el carmen de chucurí': 'A mountain paradise famous for its world-class cacao production and rich tropical biodiversity.',
    'los santos': 'Perched on a scenic plateau, this town offers stunning canyon views and is known for its high-quality specialty coffee.',
    'oiba': 'The "Honey City of Colombia," renowned for its red-clay colonial architecture and proximity to lush forests.',
    'páramo': 'A gateway to nature, home to the spectacular Juan Curí waterfalls and lush subtropical landscapes.',
    'puente nacional': 'A historic colonial town where important independence movements took place, preserved with beautiful architecture.',
    'san vicente de chucurí': 'The "Cacao Capital of Colombia," a vibrant town surrounded by lush plantations and the Yariguíes National Park.',
    'suaita': 'A town of industry and nature, housing the ruins of Colombia\'s first textile factory and the grand Los Caballeros waterfall.',
    'valle de san josé': 'A charming colonial village world-famous for its traditional chorizos and preserved historical atmosphere.',
    'cepitá': 'A hidden gem deep within the Chicamocha Canyon, characterized by its arid beauty and colonial tranquility.',
    'pinchote': 'Birthplace of the heroine Antonia Santos, this peaceful colonial town preserves a rich historical heritage.',
    'santander-albania': 'A peaceful mountain town with stunning green landscapes and traditional colonial charm.',
    'betulia': 'Known for its scenic beauty and traditional coffee-growing heritage, surrounded by misty Andean peaks.',
    'bolívar': 'A historic and resilient town in southern Santander, known for its colonial legacy and mountain vistas.',
    'capitanejo': 'Perched on the banks of the Chicamocha River, known for its hot climate, goat breeding, and strategic mountain location.',
    'cerrito': 'An Andean town featuring high-altitude "páramo" landscapes and traditional stone architecture.',
    'contratación': 'A town with a unique history and heritage architecture, preserved with stories of resilience and community.',
    'florián': 'Home to the spectacular "Ventanas de Tisquizoque," a majestic waterfall exiting through a massive natural cave.',
    'gambita': 'Birthplace of musician Luis A. Calvo, a paradise of waterfalls including the grand Manto de la Virgen.',
    'jordán': 'A well-preserved "ghost town" at the bottom of the Chicamocha Canyon, offering a step back in time with its stone houses.',
    'la belleza': 'A hidden treasure known for its mystical limestone caves and lush, diverse agricultural landscapes.',
    'landázuri': 'A tropical paradise in the mountains, famous for its cacao plantations and misty forest trails.',
    'lebríja': 'The "Pineapple Capital of Colombia," a heights-positioned town known for its agricultural wealth and panoramic views.',
    'mogotes': 'A historic town near San Gil, renowned for its traditional handicrafts, scenic valleys, and colonial streets.',
    'puerto wilches': 'A strategic tropical port on the Magdalena River, surrounded by palm plantations and rich river ecosystems.',
    'santander-san andrés': 'The majestic gateway to García Rovira, featuring a landmark colonial church and a historic center perched atop dramatic Andean slopes.',
    'santander-sabana de torres': 'A strategic agricultural and industrial hub in the Magdalena Medio, known for its strategic location and tropical abundance.',
    'santander-rionegro': 'A warm-climate gem known for its cacao tradition, offering a vibrant community atmosphere nestled among lush green hills.',
    'santander-california': 'A historic high-altitude mining town with colonial architecture clinging to mist-covered peaks in the Soto Norte region.',
    'santander-vetas': 'One of the highest towns in Colombia, a traditional mining center surrounded by the ethereal beauty of the Santurbán páramo.',
    'santander-matanza': 'The colorful gateway to Soto Norte, preserving beautiful colonial facades amidst a landscape of lush green mountains.',
    'santander-suratá': 'An Andean paradise of cold climate and steep slopes, known for its historic mountain charm and misty landscapes.',
    'santander-tona': 'A serene high-altitude town with deep religious traditions, surrounded by the silence and mist of the Andean peaks.',
    'santander-simacota': 'Birthplace of the Comuneros movement, this peaceful village preserves historic stone houses and a legacy of Colombian independence.',
    'santander-sucre': 'A hidden mountain treasure in the Opón region, known for its rugged geography, rich biodiversity, and traditional rural life.',
    'santander-la paz': 'A peaceful southern destination famous for its traditional stone-paved streets and majestic mountain views.',
    'santander-el playón': 'A strategic mountain town on the northern highway, surrounded by dense tropical forests and misty green landscapes.',
    'santander-puerto parra': 'A biodiversity-rich river port in the Magdalena Medio, where the wetlands meet the tropical forest along the railway.',
    'santander-aguada': 'A tranquil jewel of the Vélez province, known for its peaceful colonial atmosphere and surrounding traditional farms.',
    'santander-cabrera': 'A charming colonial town in the Guanentá province, preserving its stone-paved streets and traditional Santander architecture.',
    'santander-carcasí': 'A remote mountain treasure in García Rovira, surrounded by dramatic cliffs and a peaceful Andean atmosphere.',
    'santander-charta': 'A lush mountain town in the Soto region, famous for its abundant water sources and beautiful green landscapes.',
    'santander-chipatá': 'A historic town in the Vélez province, featuring a unique stone-facade colonial church and a rich agricultural heritage.',
    'santander-concepción': 'A peaceful Andean village in García Rovira, known for its well-preserved colonial center and panoramic mountain views.',
    'santander-confines': 'A historic town in the Comuneros province, featuring a landmark colonial church and a legacy of Colombian independence history.',
    'santander-coromoro': 'A historic destination in the Guanentá province, where traditional colonial architecture meets lush river landscapes.',
    'santander-el guacamayo': 'A secluded mountain town in southern Santander, offering a dense tropical forest environment and rich biodiversity.',
    'santander-encino': 'A gateway to the Guanentá-Alto Fonce flora and fauna sanctuary, famous for its majestic oak forests and crystal-clear waters.',
    'santander-enciso': 'A warm-climate town in the García Rovira province, nestled in a fertile valley surrounded by lush tropical hills.',
    'santander-galán': 'A historic town named after Jose Antonio Galán, preserving a beautiful colonial church and traditional stone streets.',
    'santander-guaca': 'A destination of deep religious and colonial tradition, surrounded by majestic Andean peaks and traditional farms.',
    'santander-guapotá': 'A peaceful rural town in the Comuneros province, known for its coffee-growing traditions and rolling green hills.',
    'santander-guavatá': 'The "World Capital of Guava," a traditional town in the Vélez province surrounded by lush orchards and green mountains.',
    'santander-güepsa': 'A traditional town in the Vélez province, known for its sweet guava bocadillo production and colonial charm.',
    'santander-jesús maría': 'A peaceful colonial town in the Vélez province, featuring a landmark church and surrounded by rolling green agricultural hills.',
    'santander-macaravita': 'A majestic high-altitude town in García Rovira, offering dramatic views of Andean canyons and traditional stone streets.',
    'santander-molagavita': 'A scenic mountain destination in the García Rovira province, overlooking the spectacular landscapes of the Chicamocha region.',
    'santander-ocamonte': 'A charming colonial-style town in the Guanentá province, famous for its high-quality coffee and lush environmental beauty.',
    'santander-onzaga': 'A historic mountain town founded on ancestral lands, known for its colonial architecture and crystal-clear Andean streams.',
    'santander-palmar': 'A tranquil rural jewel in the Comuneros province, characterized by its namesake palm trees and peaceful community atmosphere.',
    'santander-san joaquín': 'The "Cold Pearl of Santander," a picturesque mountain town in Guanentá known for its mist-shrouded peaks and colonial church.',
    'santander-san miguel': 'A majestic remote town in García Rovira, nestled between dramatic limestone cliffs and lush hidden valleys.',
    'santander-santa bárbara': 'A high-altitude Soto treasure, where colonial houses sit amidst the clouds in a beautiful páramo-edge landscape.',
    'santander-san josé de miranda': 'A picturesque town in García Rovira, featuring a striking twin-towered church and a rich religious and agricultural heritage.',
    'santander-santa helena del opón': 'A remote paradise in the Opón mountains, surrounded by pristine tropical forests and spectacular hidden waterfalls.',
    'santander-san benito': 'A peaceful Vélez province town, preserving its traditional way of life among green hills and traditional sugar cane farms.',
    'santander-hato': 'A historic colonial town in the Comuneros province, known for its stone-paved streets and deep connection to the independence era.',
    'santander-chimá': 'A spiritual and historic town in the Comuneros province, site of the miraculous Virgin of the Rock and traditional architecture.',
    'santander-el peñón': 'A land of dramatic limestone formations and deep caves, offering extreme natural beauty and a traditional Santander mountain atmosphere.',

    // Antioquia
    'guatapé': 'A vibrant town famous for its incredibly colorful "zócalos" and the massive Peñol Rock offering 360-degree views.',
    'guatape': 'A vibrant town famous for its incredibly colorful "zócalos" and the massive Peñol Rock offering 360-degree views.',
    'jardín': 'One of Colombia\'s most beautiful towns, characterized by its flower-filled balconies and preserving colonial architecture.',
    'jardin': 'One of Colombia\'s most beautiful towns, characterized by its flower-filled balconies and preserving colonial architecture.',
    'jericó': 'The birthplace of Mother Laura, famous for its traditional leather "carriel" bags and stunning mountain scenery.',
    'jerico': 'The birthplace of Mother Laura, famous for its traditional leather "carriel" bags and stunning mountain scenery.',
    'santafé de antioquia': 'The historical capital of the department, featuring remarkable colonial architecture and the iconic Bridge of the West.',
    'santafe de antioquia': 'The historical capital of the department, featuring remarkable colonial architecture and the iconic Bridge of the West.',
    'santa rosa de osos': 'A high-altitude town known for its dairy traditions and the "Cathedral of the North."',
    'támesis': 'An ecological paradise known for its pre-Columbian petroglyphs and diverse hiking trails.',
    'tamesis': 'An ecological paradise known for its pre-Columbian petroglyphs and diverse hiking trails.',
    'rionegro': 'A historical industrial hub and the gateway to the beautiful San Nicolás valley.',
    'envigado': 'A traditional town that maintains a small-town feel within the metro area, famous for its gastronomy and festivals.',
    'sabaneta': 'The smallest municipality in Colombia, known for its vibrant town square and traditional buñuelos.',
    'itagüí': 'An industrial city known for its cultural centers and vibrant street murals.',
    'itagui': 'An industrial city known for its cultural centers and vibrant street murals.',
    'la ceja': 'A peaceful valley town famous for its flower exports and its strong cycling culture.',
    'el carmen de viboral': 'Famous worldwide for its unique, hand-painted ceramic traditions and artistic streets.',

    // Bolívar
    'cartagena': 'Cartagena is a Caribbean port city known for its colonial architecture, colorful streets, and historic fortifications including the San Felipe de Barajas Castle.',
    'mompós': 'Santa Cruz de Mompós is a UNESCO World Heritage site frozen in time, famous for its colonial architecture and its intricate filigree jewelry.',
    'san jacinto': 'San Jacinto is a cultural hub in the Montes de María, world-renowned for its artisanal hammocks, traditional Gaita music, and rich indigenous heritage.',
    'magangué': 'Known as the "City of Rivers," Magangué is a major commercial port at the confluence of the Magdalena, Cauca, and San Jorge rivers.',
    'el carmen de bolívar': 'Located in the heart of the Montes de María, El Carmen de Bolívar is an agricultural center famous for its cultural resilience and delicious local gastronomy.',
    'turbaco': 'A scenic retreat near Cartagena, Turbaco is known for its cool climate, botanical gardens, and prehistoric mud volcanoes.',
    'san juan nepomuceno': 'Home to the Los Colorados Sanctuary, San Juan Nepomuceno offers a unique glimpse into the tropical dry forest and rich local traditions.',
    'santa rosa del sur': 'Nestled in the high mountains of the Serranía de San Lucas, Santa Rosa del Sur is a vibrant town known for its emerald mines and stunning mountain landscapes.',
    'mahates': 'Mahates is the gateway to San Basilio de Palenque, the first free town in the Americas and a UNESCO Intangible Cultural Heritage site for its unique language and traditions.',
    'arjona': 'Arjona is an agricultural powerhouse famous for its traditional "Bollo Limón" and vibrant celebrations of Caribbean culture.',
    'maría la baja': 'Surrounded by fertile plains and scenic marshlands, María la Baja is a major rice and African palm producer with a rich African-descendant heritage.',
    'bolivar-villanueva': 'Villanueva is a tranquil town in the lower Bolívar plains, known for its colonial church and being a center for traditional livestock and agricultural trade.',
    'bolivar-santa rosa': 'Santa Rosa, known for its warm Caribbean atmosphere and colonial influence, is a peaceful gateway to the northern plains of Bolívar.',
    'clemencia': 'Clemencia is a charming agricultural town near the Caribbean coast, known for its lush vegetation and traditional rural hospitality.',
    'bolivar-calamar': 'Strategically located where the Canal del Dique meets the Magdalena River, Calamar is a historic river port with deep ties to Colombian transportation history.',
    'san estanislao': 'Also known as Arenal, San Estanislao is a vibrant river town with a rich cultural heritage and traditional religious celebrations.',
    'el guamo': 'Nestled in the Montes de María, El Guamo is an agricultural center known for its diverse crops and its resilient, welcoming community.',
    'bolivar-córdoba': 'Córdoba is a historic town on the banks of the Magdalena River, celebrated for its colonial church and its importance in regional trade.',
    'soplaviento': 'Soplaviento sits gracefully along the Canal del Dique, where fishing and river traditions define the local way of life and culture.',
    'bolivar-san cristóbal': 'A picturesque town on the Canal del Dique, San Cristóbal is known for its traditional fishing economy and its scenic water landscapes.',
    'zambrano': 'Zambrano is a major river port on the Magdalena, offering stunning sunrise views and serving as a key gateway to the lower Bolívar plains.',
    'pinillos': 'Located where the Magdalena River branches into the Mompós depression, Pinillos is a land of water and history with a unique riverine identity.',
    'tiquisio': 'Tiquisio is a vibrant town in southern Bolívar, known for its rich mining heritage and its strategic location in the fertile San Jorge river basin.'
};

export function getCityOverview(cityName: string, defaultDescription?: string, departmentName?: string): string {
    const name = cityName.toLowerCase();
    const dept = departmentName?.toLowerCase();

    // Check for specific department-city mapping first to handle name collisions
    if (dept) {
        const specificKey = `${dept}-${name}`;
        if (cityOverviews[specificKey]) return cityOverviews[specificKey];
    }

    // Check for direct matches
    if (cityOverviews[name]) return cityOverviews[name];

    // Check for partial matches
    for (const [key, value] of Object.entries(cityOverviews)) {
        if (name === key || name.includes(key) || key.includes(name)) {
            return value;
        }
    }

    return defaultDescription || `Discover the beauty and culture of ${cityName}, a unique destination in Colombia.`;
}
