export const departmentDescriptions: Record<string, string> = {
    'Amazonas': 'A vast region covered by the Amazon rainforest, known for its incredible biodiversity, indigenous cultures, and the mighty Amazon River.',
    'Antioquia': 'A mountainous department famous for its coffee plantations, flower festivals, and the transformation of its capital, Medellín.',
    'Arauca': 'Located in the Orinoquía region, known for its vast plains (llanos), cattle ranching culture, and breathtaking sunsets.',
    'Atlántico': 'Home to Barranquilla and its world-famous Carnival, this department offers a blend of Caribbean culture, history, and commerce.',
    'Bolívar': 'Famous for Cartagena, a colonial jewel and UNESCO World Heritage site, offering history, beautiful beaches, and vibrant culture.',
    'Boyacá': 'Known for its colonial towns like Villa de Leyva, rich history of independence battles, and beautiful Andean landscapes.',
    'Caldas': 'Part of the Coffee Cultural Landscape, offering thermal springs, the Nevado del Ruiz volcano, and rich coffee traditions.',
    'Caquetá': 'The gateway to the Amazon, offering unique ecotourism experiences, rivers, and untouched natural beauty.',
    'Casanare': 'A land of vast plains and wildlife, perfect for safari-like experiences to see capybaras, anacondas, and hundreds of bird species.',
    'Cauca': 'A culturally diverse region with strong indigenous heritage, archaeological sites like Tierradentro, and colonial Popayán.',
    'Cesar': 'The cradle of Vallenato music, offering a mix of Sierra Nevada mountains and warm plains.',
    'Chocó': 'One of the wettest and most biodiverse places on Earth, where the jungle meets the Pacific and Caribbean oceans.',
    'Córdoba': 'Known for its cattle ranching, fertile plains, and coastal towns offering a relaxed Caribbean atmosphere.',
    'Cundinamarca': 'The heart of Colombia, home to the capital Bogotá, salt cathedrals, lagoons, and diverse climates.',
    'Guainía': 'Home to the breathtaking Cerros de Mavecure, this Amazonian region offers unique rock formations and river landscapes.',
    'Guaviare': 'A meeting point of the Amazon and Orinoquía, known for ancient rock paintings, distinctive rivers, and jungle adventures.',
    'Huila': 'Famous for the Tatacoa Desert and the San Agustín Archaeological Park, a UNESCO World Heritage site.',
    'La Guajira': 'A desert peninsula meeting the Caribbean Sea, home to the Wayuu people and stunning landscapes like Cabo de la Vela.',
    'Magdalena': 'Home to the Sierra Nevada de Santa Marta and Tayrona National Park, offering snow-capped peaks near tropical beaches.',
    'Meta': 'The heart of the Llanos Orientales, known for Caño Cristales (the River of Five Colors) and cowboy culture.',
    'Nariño': 'A region of volcanoes, the spectacular Las Lajas Sanctuary, and a unique blend of Andean and Pacific cultures.',
    'Norte de Santander': 'A border region with Venezuela, offering historical sites, national parks, and the unique Catatumbo lightning phenomenon.',
    'Putumayo': 'A gateway to the Amazon with a spiritual heritage, known for its biodiversity, waterfalls, and indigenous cultures.',
    'Quindío': 'The smallest department but the heart of the Coffee Region, home to the Cocora Valley and its giant wax palms.',
    'Risaralda': 'Part of the Coffee Triangle, known for its thermal springs, birdwatching, and the charming town of Marsella.',
    'San Andrés y Providencia': 'A Caribbean archipelago known for its Sea of Seven Colors, coral reefs, and distinct Raizal culture.',
    'Santander': 'The land of adventure sports, the majestic Chicamocha Canyon, and beautiful colonial towns like Barichara.',
    'Sucre': 'Offers beautiful gulf beaches, marshes, and a relaxed Caribbean pace of life.',
    'Tolima': 'A land of music, tamales, and diverse landscapes ranging from the Magdalena River valley to snowy volcanoes.',
    'Valle del Cauca': 'Home to Cali, the capital of Salsa, and diverse landscapes from sugar cane fields to the Pacific coast.',
    'Vaupés': 'A remote Amazonian region defined by its rivers, mighty waterfalls like Jirijirimo, and indigenous heritage.',
    'Vichada': 'A vast territory of plains and rivers on the Venezuelan border, offering raw nature and excellent fishing.',
    'Bogotá, D.C.': 'The capital city and a district of its own, a high-altitude cultural hub with museums, history, and modern dining.',
    'Bogotá': 'The capital city and a district of its own, a high-altitude cultural hub with museums, history, and modern dining.'
};
